TeamPorcupine/ProjectPorcupine

README.md
There should be an email address in the readme so that people can contact the maintainer directly.
=> Added email address to readme file.

README.md
This will help people find the YouTube tutorials explaining how Project Porcupine works!
=> Add a YouTube link to the Readme file

CONTRIBUTING.md
Added a CONTRIBUTING.md with links to documentaion , YT video and the guidelines from the readme
=> Create contributing guidelines

Assets/Scripts/Controllers/MouseController.cs
A small change, but hopefully very useful.
=> Added ability to dismiss build mode with right click

README.md
I moved two periods from within the parenthesis, to outside the
parenthesis.  This makes the Readme punctuated properly.
=> Modify the Readme's Punctuation

Assets/Scripts/Models/Character.cs
This seeks to address issues discussed in #20 -- though obviously this is just one file.
We should lock in on this ASAP because this is almost certainly going to make a lot of other merges conflict.
=> Reformat Character.cs to fit proposed coming style

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/ISelectable.cs, Assets/Scripts/Models/ISelectable.cs.meta, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/UI/SelectionInfoTextField.cs, CONTRIBUTING.md, README.md
=> Rename ISelectableInterface to ISelectable

Assets/Scripts/Models/Tile.cs
Auto-reformatting broke a line, I fixed it, so that `Tile.cs` compiles again.
=> Hotfix to Tile.cs

Assets/Scripts/Models/Character.cs
Took the huge function body and divided it into a few logical functions. Also added/reworked/deleted some comments where appropriate and layed some foundadtions for further improvements to the job queue, i.e. Dumping of Inventories. I will also open an issue discussing the inventory-dumping further.
=> Code refactoring of Character's job handling functions

Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Data/Furniture.xml
Simply added the ability to add a description to the furniture in XML that replaces the default "This is a piece of furniture."
=> Added descriptions to Furnitures.

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/InventoryManager.cs
#43 - Fixed end tile on old destination stockpile check
=> Fixed pathfinding issues

CONTRIBUTING.md
=> Request that screenshots be included.

Assets/StreamingAssets/Localization/es_ES.lang
As @frankitox16 mentioned in #124 this is a better translation. Don't translate while asleep kids :D
=> fix mining drone station es translation

CONTRIBUTING.md
Fixed some ambiguity in the Style Guidelines and added @lameox's TL;DR for our coding style.
=> Specify Coding Style for Contributions according to #182

CONTRIBUTING.md
In reference to issue #17.
Adds section saying that we are using unity 5.4 and that pull request have to build in 5.4 to be valid.
=> Added unity version to  CONTRIBUTING.md

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxLoadGame.cs, Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs, Assets/UI/DialogListItem.cs
=> Added double Click to Load and Save Dialog

GIT_TUTORIAL
This is sooooo much nicer of a way to write that line.
=> Changed capitalization on HHGTG line

.gitignore, Assets/Settings.StyleCop, Assets/Settings.StyleCop.meta
These settings files wont affect anyone not using StyleCop.
=> Added StyleCop settings.

Assets/Scripts/Controllers/GameEventManager.cs, Assets/Scripts/Controllers/GameEventManager.cs.meta, Assets/Scripts/Models/GameEvent.cs, Assets/Scripts/Models/GameEvent.cs.meta, Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/Models/GameEventActions.cs.meta, Assets/StreamingAssets/GameEvents.meta, Assets/StreamingAssets/GameEvents/SpacePirateEvents.xml, Assets/StreamingAssets/GameEvents/SpacePirateEvents.xml.meta, Assets/StreamingAssets/LUA/GameEvent.lua, Assets/StreamingAssets/LUA/GameEvent.lua.meta, Assets/_SCENE_.unity
Adds EventSystem, events can be created in the StreamingAssets/GameEvents folder as xml code. (e.g. attacks from space pirates, meteors, a new crew member,  merchants)
=> EventSystem (New crew member, pirates, etc)

Assets/Scripts/Controllers/MouseController.cs
The commit with the dragTypes ( #259 ) wants to look for tiles in the furniturePrototypes.
Bug appears only when a new game is started and building floor is the first thing you do,
=> Several fixes with the DragType implementaion

Assets/Scripts/Controllers/GameEventManager.cs, Assets/Scripts/Models/GameEvent.cs, Assets/StreamingAssets/GameEvents/SpacePirateEvents.xml
Should temporarily fix  the issue with Characters ( #331  ) until better pathfinding is in place
=> Limits the repeats a GameEvent has

Assets/StreamingAssets/Localization/no-BM.lang.meta
=> Added missing localization meta file no-BM.lang.meta

Assets/StreamingAssets/Data/Furniture.xml
Adds typeTags to Airlock and Metal Smelter.
=> Add Missing typeTags

CONTRIBUTING.md
In an effort to help combat some of the common PR issues we keep seeing, I have produced a new video-tutorial and updated CONTRIBUTING.md to reflect the example workflow.
This explains how to pull changes from upstream, how to rebase, and how to resolve merge conflicts.
=> CONTRIBUTING changes: Command line & conflict resolution

Assets/Resources/Sounds/AccessDenied.wav.meta, Assets/Resources/Sounds/AlienSpaceship.wav.meta, Assets/Resources/Sounds/Beacon.wav.meta, Assets/Resources/Sounds/CallSignal.wav.meta, Assets/Resources/Sounds/Gunshot.wav.meta, Assets/Resources/Sounds/Hammer1.wav.meta, Assets/Resources/Sounds/HeartbeatHuman.wav.meta, Assets/Resources/Sounds/HullHit.wav.meta, Assets/Resources/Sounds/Laser1.wav.meta, Assets/Resources/Sounds/Laser2.wav.meta, Assets/Resources/Sounds/OxygenGenerator.wav.meta, Assets/Resources/Sounds/Pickaxe1.wav.meta, Assets/Resources/Sounds/PowerDown.wav.meta, Assets/Resources/Sounds/PowerDown2.wav.meta
These should probably have been part of #368.
=> Added missing meta files.

Assets/_SCENE_.unity
Checked "Pixel Perfect" option in Canvas to make UI Text sharper.
Before:
After:
=> Make UI pixel perfect

README.md
The Issues page is not the best place to vote/prioritize features and develop a roadmap.  http://feathub.com/ (suggested by @RodRitter) is a simple site that lets us easily see which features should be made a priority.
We don't need to put every little fix there.  It's mostly about getting a feel for the overall direction / roadmap of the project.
=> README.md: Add link to Feature Voting

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/WorldController.cs
This is a very simple dev mode to aid in development. It currently has no UI connection nor any hotkeys to activate. At present the only way to turn it on is by setting devMode in the WorldController. However, as it's public, it can be toggled on and off from the WorldController GameObject.
=> First Pass basic dev mode

Assets/_SCENE_.unity
I noticed that the scrolling for the language menu was too slow, so I slightly increased it.
I am also thinking of setting the scroll sensitivity based on the amount of options in the drop-down menu.
Haven't looked into that yet.
=> Slightly increased the scroll-sensitivity for the language dropdown menu

Assets/Scripts/UI/LanguageDropdownUpdater.cs
Like I mentioned in the pull request #402.
The scroll sensitivity of the language drop down menu will be set based on the options-count.
Was easier than I initially thought :)
=> Dynamic scroll sensitivity for the language dropdown menu

README.md
A simple ToS with links to the different parts of the README.md
=> Add Table of Content README.md

Assets/UI/DialogListItem.cs
=> Formatted DialogListitem to follow project convention

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxLoadSaveGame.cs, Assets/Scripts/UI/LanguageDropdownUpdater.cs
The same feature as in #406 for the save/load dialog.
=> Dynamic scroll sensitivity for the save/load dialog

Assets/Scripts/Controllers/MouseController.cs
If in the select mode, and you right click on a job, it will cancel that
job.
=> Added Canceling to Jobs when in select mode.

Assets/Scripts/Controllers/GameEventManager.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/GameEvent.cs, Assets/StreamingAssets/GameEvents/SpacePirateEvents.xml
So this make Repeat an optional parameter, if maxRepeats is set to 0 or less it repeats unlimited. Also fixes the character moonsharpuserdata issue
=> More GameEvent fixes

Assets/_SCENE_.unity
=> Anchor Right Menu to bottom right

Assets/StreamingAssets/Images/Inventory/Copper Wire.png.meta, Assets/StreamingAssets/Images/Inventory/Copper Wire.xml.meta
Should have been included in #104, but missed it.
=> Adding meta files for Copper Wire

Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Localization/LocalizationLoader.cs, Assets/Scripts/UI/LanguageDropdownUpdater.cs, Assets/Scripts/Utilities/Settings.cs, Assets/Scripts/Utilities/Settings.cs.meta, Assets/StreamingAssets/Settings.meta, Assets/StreamingAssets/Settings/Settings.xml, Assets/StreamingAssets/Settings/Settings.xml.meta
Old branch was a mess and had unneed file modifications in it , Created
a clean branch and updated localisation code to use Settings class
=> new branch for xml settings

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Models/Furniture.cs
Furniture updates surrounding furniture when needed, and spritecontroller hotfix for door & airlock rotation
=> Fixing door rotation and updating surrounding furniture when deconstructing

Settings.StyleCop
Resolves #447 
This includes the fix from #447, but also fixes most StyleCop issues.
=> Bjubes ui button toggle hotifx

Assets/Scripts/Models/Character.cs
The log is pretty busy if a character can't find the path to a job.
=> Fix the errors when we cant find a path to the job

Assets/Scripts/Models/WorldGenerator.cs, Assets/StreamingAssets/Data/WorldGenerator.xml, Assets/StreamingAssets/Data/WorldGenerator.xml.meta
Also made it easy to add new ressources to an asteroid, due to the xml files!
=> Made WorldGenerator getting it's settings from an xml file

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/PowerSystem.cs
PowerSystem has one list of all power related furniture.
=> Refactoring of PowerSystem

CONTRIBUTING.md
A simple ToS with links to the different parts of the CONTRIBUTING.md just like in README.md
=> Add Table of Content to CONTRIBUTING.md

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/PowerSystem.cs
Fixed bug after refactoring made on #484
Bug related to #460 and #434
=> Fixed bug when removing power generator

Assets/Scripts/Models/WorldGenerator.cs
Simple fix... stacksize gets set maxstacksize if it is over max
=> Some much needed bug fixes in the worldgenerator

README.md
=> added discord link

Assets/StreamingAssets/LUA/Furniture.lua
fixes #559 
If you wonder, why there are so many changed lines, that's because my editors (tried 3) wouldn't save the file without reformatting some of the lines :/
=> Fix for metal smelter issue

Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Utilities/Settings.cs
Wrapper functions for set and get , should make useage of the settings sytem easy and clean
=> Wrapper functions for set and get in Settings.cs

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxLoadGame.cs
Removed "Using UnityEditor;" line and cleaned up the code. Functionality remains the same but this doesn't block building the project to a stand-alone program.
This supersedes #456
=> Clean dependency

Assets/Scripts/Controllers/BuildModeController.cs
Removed unused "using", moved private things below public things and changed white space.
=> BuildModeController now passes the StyleCop test.

Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs, Assets/StreamingAssets/Settings/Settings.xml
DialogBoxSettings.cs now uses the new wrapper functions in Settings.cs
to save and load settings with cleaner code
=> updated DialogBoxSettings.cs to use new Settings.cs

Assets/Scripts/Models/WorldGenerator.cs, Assets/StreamingAssets/Data/WorldGenerator.xml
=> Fixed spelling in WorldGenerator.cs and xml. Fixes #582.

Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs
As said in the title, **I have edited the quality setting in order for it to work**.
Also, this fixes #565 which I have already closed.
_(It took me some time to understand that I could fix #565 without editing the SCENE file)_
=> Implemented OnQualityChange() in DialogBoxSettings.cs

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Job.cs
=> Ensure remove designation removes both the image and job

.gitignore, Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/StreamingAssets/Localization.meta
*And i will test all the thins later, for now I blame lack of unit testing*
=> Hotfix for 608... Last one, i promise

Assets/Scripts/Controllers/MouseController.cs, Assets/StreamingAssets/Data/Furniture.xml
I won't merge this in myself. I'll wait for another mod to look it over first. @Mizipzor @WardBenjamin @vogonistic What is the process for moderator contributions?
I added a new drag type for furniture: `<DragType>path</DragType>`
It's a very rudimentary system for laying down pipe-like furniture. At the moment it does have an x-bias but that can be improved over time with some better logic.
=> Added Path drag type - Preparing for conduits & piping

Assets/StreamingAssets/Data/Furniture.xml
Earlier the characters stood next to the chair when smelting, now they sit on the chair.
=> Job spot is in proper position for smelter

CONTRIBUTING.md
changed the ' to \` so that it is consistent with the furniture ones
=> Fix Inventory Standard

Assets/StreamingAssets/LUA/Furniture.lua
Reverts TeamPorcupine/ProjectPorcupine#635 -- just noticed I used ChangeParameter when it should be SetParameter -- very sorry
=> Fixing metal smelter bug issue #577 (with hacks)

Assets/Scripts/Models/WorldGenerator.cs
Overlooked 2 little bugs while testing x.x'
=> 2 little fixes for WorldGen 

Assets/Scripts/Controllers/FurnitureSpriteController.cs
Very small change... just allows future extensibility (easier implementation of new door types)
=> door rotation properly based on xml properties rather than hard coded

Assets/Scripts/Models/WorldGenerator.cs, Assets/StreamingAssets/Data/WorldGenerator.xml
Everyone seemed fine with the weight based system.
closes #671
=> Changed the resource spawn chance to the weight based system

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Controllers/TileSpriteController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/TileType.cs, Assets/Scripts/Models/TileType.cs.meta, Assets/Scripts/Models/World.cs, Assets/Scripts/Models/WorldGenerator.cs, Assets/Scripts/UI/InGameUI/ConstructionMenu.cs, Assets/Scripts/UI/InGameUI/FloorMenu.cs, Assets/StreamingAssets/Data/Tiles.xml, Assets/StreamingAssets/Data/Tiles.xml.meta, Assets/StreamingAssets/LUA/Tile.lua, Assets/StreamingAssets/LUA/Tile.lua.meta, Assets/_SCENE_.unity
This adds xml and lua definable tiles with support for mods. Changes the scene to make the tile build menu generated on the fly.
=> Moddable tiles

Assets/Scripts/UI/FurnitureBuildMenu.cs
Pretty straightforward... (that commit name was unintended, got a couple of troubles getting used to git bash ^^)
=> [UI] Build menu closes after selecting furniture to build

Assets/Scripts/Models/World.cs
The names of my caracters was the whole text file.
=> Fix caracter names parse text file

Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/Scripts/Localization/LocalizationLoader.cs, Assets/Scripts/Localization/LocalizationTable.cs, Assets/Scripts/Localization/TextLocalizer.cs, Assets/Scripts/UI/FurnitureBuildMenu.cs, Assets/Scripts/UI/LanguageDropdownUpdater.cs
Also made StyleCop happy because I was modifying those files anyway.
=> Fixed the need to restart after downloading the fresh localization.

Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/Scripts/Localization/LocalizationLoader.cs
=> [Conflicts][WIP] Horrible error fix, Modified the localization version check system so it will check for the latest commit hash.

Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/Scripts/Localization/LocalizationLoader.cs, Assets/Scripts/Localization/LocalizationTable.cs
Had to add ToString() in a few places. Checked exceptions and output is identical
Removed a line break that truncated the log message rendering it useless.
=> Switched to Uberlogger and fixed a typo

Assets/Scripts/UI/Overlay/OverlayDescriptor.cs, Assets/Scripts/UI/Overlay/OverlayMap.cs, Assets/Scripts/Utilities/Settings.cs, Assets/Scripts/Utilities/SimplePool.cs
Switched over to Uberlogger. Left commented debug calls in.
=> Fix log ui debug.ui/overlay

Assets/Scripts/Utilities/Settings.cs, Assets/Scripts/Utilities/SimplePool.cs
Checked Utilities folder and changed over logging from regular logging to Uberlogger. I left one `Debug.Log` call, a call that is very likely to produce several lines. Because Uberlogger doesn't handle multiple lines at all. I also skipped a file `ModUtils´.cs` that already has been switch over but not yet merged #723
=> Switched over to Uberlogger. Removed a commented debug call. Fixed typo.

Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/Scripts/Localization/LocalizationLoader.cs
=> [Small]Follow up on PR #720. Missed one instance and removed unneeded comment.

Assets/UberLogger/Editor/UberLoggerEditorWindow.cs
It's not perfect, but it works.
=> Add Autoscroll to UberLogger

Assets/Scripts/Utilities/ModUtils.cs, Assets/StreamingAssets/LUA/Furniture.lua
=> Implement UberLogger functions in ModUtils

Assets/Scripts/Controllers/MouseController.cs
Made zoom focus on mouse position like in #526
=> Fixed mouse zoom focus position not working from #678

Assets/Scripts/Localization/LocalizationTable.cs
=> [small] Changed localization missing log to info level

Assets/StreamingAssets/LUA/Furniture.lua
I mainly fixed the metal smelter.
While I was at it, I also reformatted the whole file to make it readable.
=> Fix for Metal Smelter and Cloning Pod (also code clean up)

Assets/Scripts/Controllers/CameraController.cs, Assets/Scripts/Controllers/CameraController.cs.meta, Assets/Scripts/Controllers/KeyboardController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/WorldController.cs
Added the ability to zoom with the Keyboard (PageUp/PageDown).
This fixes issue #762.
=> Zoom with Keyboard (PageUp/PageDown)

Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Controllers/KeyboardController.cs, Assets/Scripts/Controllers/MouseController.cs
Basically #757 just with the next set of controllers.
Implemented UberLogger logging for:
- InventorySpriteController
- JobSpriteController
- KeyboardController
- MouseController
=> UberLogger for more controllers

Assets/Scripts/Models/Temperature.cs, Assets/StreamingAssets/Data/Furniture.xml
Removes a warning and an error (2 lines fix).
- FunctioName wrong in Furniture.xml
- Too strict warning warning in Temperature
=> Fix small issues

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/ISelectable.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/Utilities/VisualPath.cs, Assets/Scripts/Utilities/VisualPath.cs.meta
With this PR we are now able to see where the characters are going similar to RimWorld. Once someone implements being able to select characters, then this should be changed to only show who is currently selected. But i think this is a good addition right now to help show where the characters are going and easily see if there is any hiccups in the path. All of the line drawing was done with GL and to my knowledge, should be pretty efficient but this is my first time actually working with GL.
Edit: removed second picture because now only one character path will be shown.
=> Added visual path for selected characters

Assets/StreamingAssets/Data/Furniture.xml
*Updated to use 4/8/12/16 spaces not tab.
*Rearranged tags so every furn uses the same order.
=> Style update adressing problems in #686

Assets/Scripts/Localization/LocalizationDownloader.cs, Assets/Scripts/Localization/LocalizationLoader.cs, Assets/Scripts/Models/World.cs
Someone maintaining this later will have less trouble understanding this... thing >.>
=> LocalizationDownloader refactor

Assets/StreamingAssets/LUA/Furniture.lua
Nothing major, but every CPU cycle saved in Update() is a good thing IMHO
=> small lua optimization

Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/Models/QuestActions.cs, Assets/Scripts/Settings.meta, Assets/StreamingAssets/Data/CharacterNames.txt, Assets/StreamingAssets/LUA/Furniture.lua, Assets/StreamingAssets/LUA/GameEvent.lua, Assets/StreamingAssets/LUA/Quest.lua, Assets/StreamingAssets/LUA/Tile.lua
- Inserts license headers
- Makes ModUtils accessible from GameEvent.lua and Quest.lua
- A few useful log messages (not spammy)
...
- And the best character name yet
=> Tidies lua scripts a bit

Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/TileType.cs
Made a small optimization to MovmentCost. It should be faster but not noticeably (At least on my machine).
=> Optimized MovmentCost

Assets/Scripts/Models/JobQueue.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Utilities/LuaUtilities.cs, Assets/StreamingAssets/LUA/Tile.lua
We should attempt to eliminate any case where a Lua function gets called multiple times per frame.
This is not the fix to #796 -- but it should help performance a fair bit.
=> Tile movement cost calculations moved to C#

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/QuestController.cs, Assets/Scripts/Controllers/SelectionInfo.cs, Assets/Scripts/Controllers/SoundController.cs, Assets/Scripts/Controllers/SpawnInventoryController.cs
Continuing #757 #774 
Continuing to work through the Controllers directory tidying up.
There are no Debug.Log calls to refactor in these controllers so just
doing the StyleCop changes.
- MouseController
- QuestController
- SelectionInfo
- SoundController
- SpawnInventoryController
=> StyleCop tidies of some of the controllers

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/World.cs
Character names weren't saved or loaded, and this caused characters to not be properly loaded (perhaps they were just invisible?)
=> Fix Character Saving Loading

Assets/Scripts/Models/NeedActions.cs, Assets/Scripts/Models/World.cs
A cleaner implementation of the singleton pattern, not requiring someone to explicitly call the constructor.
=> NeedActions singleton.

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/CameraController.cs, Assets/Scripts/Controllers/SpriteManager.cs, Assets/Scripts/Controllers/TileSpriteController.cs, Assets/Scripts/Controllers/WorldController.cs
Switching over to Uberlogger. 
One `Debug.Log` remains as UberLogger truncates multiline messages. Might be a candidate for removal. 
Removed a few old commented out `Debug.Log`
Started fixing StyleCop complaints until I realized I didn't quite knew how to fix everything.
=> Switched to UberLogger where appropriate. And a few style fixes

README.md
Just a little something that would have helped me out.
=> Saying that you need Unity 5.4 in README

Assets/Scripts/Models/EventAction.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryCommon.cs, Assets/Scripts/Models/InventoryManager.cs
Switched to UberLogger. First part of my pass over "Models" folder
Added missing License header.
Removed old commented out debug calls.
Removed a few debug calls that where nearly useless.
Used the "Lua" channels for a few calls that where linked to Lua functions.
NB. I was unable to test/trigger the change in Assets/Scripts/Models/Inventory.cs but it should work and in any case UberLogger passes all debug messages to Unity's console.
=> Switched to UberLogger. 

Assets/Scripts/UI/ContextMenu/ContextMenu.cs, Assets/Scripts/UI/ContextMenu/ContextMenuItem.cs
Fixed issues from StyleCop, added the license, added doc comments and replaced all the vars.
=> Fixed the code in the context menu files

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/UI/CursorInfoDisplay.cs, Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs
This in turn meant to refactor some variables in other files to not break current code.
StyleCop was enforced in those files as well.
=> Fixed StyleCop-enforced code style in WorldController.cs

Assets/Scripts/Utilities/DuplicateKeyComparer.cs
=> StyleCop-ed DuplicateKeyComparer.cs

Assets/Scripts/Utilities/LuaUtilities.cs
=> StyleCop-ed LuaUtilitys.cs

Assets/Scripts/Utilities/ModUtils.cs
Only one missing access modifyer
=> StyleCop-ed ModUtils.cs

Assets/Scripts/Pathfinding/Path_AStar.cs
Lots of changes , renamed some public methods and varibles no public
methods renamed
=> StyleCop-ed Path_AStar.cs

Assets/Scripts/Models/Quest/Quest.cs, Assets/Scripts/Models/Quest/QuestGoal.cs, Assets/Scripts/Models/Quest/QuestReward.cs, Assets/Scripts/Models/QuestActions.cs
*    /Assets/Scripts/Models/Quest/Quest.cs
*    /Assets/Scripts/Models/Quest/QuestGoal.cs
*    /Assets/Scripts/Models/Quest/QuestReward.cs
*    /Assets/Scripts/Models/QuestActions.cs
=> StyleCop fixes /Assets/Scripts/Models/QuestActions and /Assets/Scripts/Models/Quest/*

Assets/Editor/LivePowerSystemTest.cs, Assets/Editor/ParametersEditorTest.cs, Assets/Editor/PowerGridTest.cs
- /Assets/Editor/LivePowerSystemTest.cs
- /Assets/Editor/ParametersEditorTest.cs
- /Assets/Editor/PowerGridTest.cs
=> StyleCop-ed Editor-Tests

Assets/Scripts/Models/ContextMenu/ContextMenuAction.cs, Assets/Scripts/Models/ContextMenu/ContextMenuLuaAction.cs, Assets/Scripts/Models/ContextMenu/IContextActionProvider.cs
* /Assets/Scripts/Models/ContextMenu/ContextMenuAction.cs
* /Assets/Scripts/Models/ContextMenu/ContextMenuLuaAction.cs
* /Assets/Scripts/Models/ContextMenu/IContextActionProvider.cs
=> StyleCop fixes for Assets/Scripts/Models/ContextMenu/*

Assets/Scripts/UI/Overlay/OverlayDescriptor.cs, Assets/Scripts/UI/Overlay/OverlayMap.cs
- /Assets/Scripts/UI/Overlay/OverlayDescriptor.cs
- /Assets/Scripts/UI/Overlay/OverlayMap.cs
=> StyleCop-ed Overlay

Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Models/JobQueue.cs
Changed:
- /Assets/Scripts/Models/JobQueue.cs
- /Assets/Scripts/Controllers/JobSpriteController.cs
=> StyleCop-ed JobQueue.cs

Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/Trade/Trade.cs, Assets/Scripts/Models/Trade/TraderPrototype.cs, Assets/Scripts/Models/WorldGenerator.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/StreamingAssets/LUA/Furniture.lua
Had to make changes in 11 files.
=> StyleCop-ed Inventory.cs

Assets/UI/Editor/AutomaticVerticalSizeEditor.cs
=> StyleCop compliant now.

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/CameraController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Localization/LocalizationLoader.cs, Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs, Assets/Scripts/UI/LanguageDropdownUpdater.cs, Assets/Scripts/Utilities/Settings.cs
=> StyleCop-ed Settings.cs

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/JobQueue.cs, Assets/Scripts/Models/Need.cs, Assets/Scripts/Models/Tile.cs
As always, some refactoring was needed, so other files were changed as well.
=> StyleCop-ed Job.cs and JobSpriteController.cs

Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Models/TileType.cs
=> StyleCop-ed InventorySpriteController.cs

Assets/Scripts/UI/DialogBox/Options/DialogBoxOptions.cs, Assets/Scripts/UI/DialogBox/Quest/DialogBoxQuestItem.cs, Assets/Scripts/UI/DialogBox/Quest/DialogBoxQuests.cs, Assets/Scripts/UI/DialogBox/Quest/MainScreenQuestList.cs
* Assets/Scripts/UI/DialogBox/Options/DialogBoxOptions.cs
* Assets/Scripts/UI/DialogBox/Quest/DialogBoxQuestItem.cs
* Assets/Scripts/UI/DialogBox/Quest/DialogBoxQuests.cs
* Assets/Scripts/UI/DialogBox/Quest/MainScreenQuestList.cs
=> StyleCop fixes in UI/DialogBox/Options/* and Quest/*

Assets/Scripts/UI/ContextMenu/ContextMenuItem.cs, Assets/UI/AutomaticVerticalSize.cs, Assets/UI/DialogListItem.cs
And we should be done on the C# side of things!
=> StyleCop-ed ContextMenuItem.cs; AutomaticVerticalSize.cs and DialogListItem.cs

Assets/StreamingAssets/LUA/Furniture.lua, Assets/StreamingAssets/LUA/GameEvent.lua, Assets/StreamingAssets/LUA/Quest.lua, Assets/StreamingAssets/LUA/Tile.lua
This fixes all of the refactoring issues in the Lua files.
=> [StyleCop] Lua fixes

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/PowerSystem.cs, Assets/Scripts/Models/World.cs
Not everything could be caught by StyleCop
=> StyleCop and Refactoring of Furniture

CONTRIBUTING.md
Updated the TL;DR code example to reflect our Code Style
=> Update CONTRIBUTING.md -- StyleCop Saturday

Assets/StreamingAssets/Settings/Settings.xml
Probably this was not intended
=> Redo changes to Settings commited on #886

Assets/Scripts/Models/ContextMenu/ContextMenuAction.cs, Assets/Scripts/UI/ContextMenu/ContextMenu.cs, Assets/Scripts/Utilities/Settings.cs
Because apparently we just happily continue to break our coding standard.
=> StyleCop-ed the newly changed files

Assets/Scripts/Controllers/WorldController.cs
Added IsPaused check on call to World.UpdateCharacters()
Added comments denoting places for different update frequencies.
=> Fixed pause behaviour - Fixes #853

Assets/Scripts/Controllers/SelectionInfo.cs, Assets/Scripts/Models/Job.cs
This makes the pending job in a tile selectable
=> Make job selectable

Assets/Scripts/Models/Animation.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/JobQueue.cs, Assets/Scripts/Models/Need.cs, Assets/Scripts/Models/NeedActions.cs, Assets/Scripts/Models/Room.cs
Removed spammy debug message with no meaning. ie "Enqueued job for " was just that message every second.
SC fix on Job.cs x4
=> Moved debug calls to UberLogger. 

Assets/Scripts/Models/World.cs
Moved most `Debug.Log` to UberLogger.
Left multiline messages because UberLogger don't display the full message.
=> Moved to UberLogger. Due to number of edits World.cs deserves its own PR

Assets/Scripts/Models/Temperature.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/TileType.cs, Assets/Scripts/Models/WorldGenerator.cs
Fixed a few typos
Not all `Debug.Log` where replaced due to UberLogger inability to show multiline messages.
SC passed.
And I screwed up commit message.
=> Moved most debug calls to UberLogger. 

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Job.cs
Fixes #991 
StyleCop passed
Is now a public instance method. Call like `job.FulfillableInventoryRequirements()`.
=> Refactor FulfillableInventoryRequirements onto Job

Assets/Editor/DuplicateKeyComparerTest.cs, Assets/Editor/DuplicateKeyComparerTest.cs.meta
three tests fail , currently think its  the DuplicateKeyComparer being broken rather than the the unit test code being wrong. Would like someone to take a look and see if they agree
=> Adds Unit Test to Duplicate Key Comparer

Assets/StreamingAssets/Images/Character/char1_spacesuit.xml
Because the characters were not really where they should be.
=> Character alignment hotfix - Fixes #1011

Assets/Scripts/Controllers/BuildModeController.cs
=> [Small] Fixed Furniture Building Instantly

Assets/Scripts/Controllers/WorldController.cs
=> Fixed StyleCop issues introduced in #817

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Models/Furniture.cs
Applies to other furniture with replaceAbleFurniture as well, #272.
=> Make door buildable on pending walls #272 

Assets/Resources/UI/DB_Quests.prefab
Added mask to QuestItemScrollViewerViewBox to prevent overflow.
=> Fixes #1045

Assets/Resources/Prefab/TradeItemPrefab.prefab, Assets/Resources/UI/DB_Trade.prefab, Assets/Scripts/UI/DialogBox/Trade/DialogBoxTrade.cs, Assets/Scripts/UI/DialogBox/Trade/DialogBoxTradeItem.cs
A redo of #1068 branching correclty from upstream/master and not my fork/master
Very small PR to align the trade interface in a grid and make it readable
=> Feature/better trade ui (redo correclty)

Assets/Scripts/Models/Character.cs
Fix an error when there is no Furniture available to satify the need
=> [Small] Fix error with Needs

Assets/Scripts/Models/TileType.cs
Resolved - // TODO: Maybe cache the empty and floor tiletypes.
=> Resolved TODO in TileType

Assets/Scripts/Controllers/TimeManager.cs
KeypadPlus can actually go out of range. 
This is a fix.
=> [small] Fix timescale out of range speed

README.md
adds a travis badge to the readme. looks like this
---
rest of readme goes here
=> [Small] Add Travis Badge to Readme

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/TileType.cs, Assets/Scripts/Models/World.cs
Z and Depth not Properly saved - Fixed
Cached Tiletypes causing innacurate comparisons - Fixed
=> [HotFix] Fixes #1117

Assets/Resources/Editor.meta
I assume this was a directory that was empty which git doesn't care about.
=> Removed Editor.meta. Most have missed it last commit.

Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryCommon.cs, Assets/Scripts/Models/Prototypes/PrototypeManager.cs, Assets/StreamingAssets/Data/Inventory.xml
feature: #1075
Add category & base price in the inventory prototype (inventory common)
=> [Updated] Add base price & category to inventory prototype (inventory common)

Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
Now all machines consume power. If power is lost, machines that create jobs will cancel them and won't remake them til power is restored. This way the characters can't use the machines when there is no power.
=> Added power consumption to the rest of the machines.

Assets/Scripts/Models/Character.cs
A small tidy up of the character class trying to group functions in a logical way.
=> Tried to clean up the character class by grouping functions of similar type

Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Controllers/SpawnInventoryController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/Trade/Trade.cs, Assets/Scripts/Models/Trade/Trader.cs, Assets/Scripts/Models/Trade/TraderPrototype.cs, Assets/Scripts/Models/World.cs, Assets/Scripts/Models/WorldGenerator.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/UI/CursorInfoDisplay.cs, Assets/Scripts/UI/DialogBox/Trade/DialogBoxTrade.cs, Assets/StreamingAssets/LUA/Furniture.lua
as requested in #1109 by @Grenkin1988
=> [Manual Test requested] Fix Inventory.cs stylecop issues

Assets/Scripts/UI/Overlay/OverlayMap.cs, Assets/StreamingAssets/Overlay/overlay_functions.lua
fix for #1155. Also found an error in the overlay Lua code.
=> Fixes #1155 - Overlay drawn under tiles

Assets/Scripts/Controllers/CameraController.cs, Assets/Scripts/UI/Overlay/OverlayMap.cs
A few violations snuck in somewhere...
=> [small] Stylecopping

Assets/Scripts/UI/Overlay/OverlayMap.cs
Organizes files to not violate StyleCop Rules.
=> Fix StyleCop Violations in OverlayMap.cs

Assets/Scripts/Controllers/ModsManager.cs, Assets/Scripts/Models/Character.cs
=> Fix stats prototypes loading

Assets/Resources/UI/Headlines.prefab
The size of the Headline Box will now auto-adjust, as seen below:
=> Adjusts the size of the Headlines depending on the text

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/WorldGenerator.cs
Fix Stylecop warning in furnitures.cs documentation
=> [small] Fix Stylecop warning in furnitures.cs documentation

Assets/Scripts/Controllers/ModsManager.cs
Fix Quest Prototypes not loading
The Quest were missing in the mod manager
=> [Small] Fix Quest Prototypes not loading

Assets/Resources/UI/DB_Options.prefab
Removed the "Pathfinding Test" and "temp_trade_test" buttons from the Options dialog box.
=> Removed old testing buttons (Fixed #1186)

Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/Images/Furniture/RTG.png.meta, Assets/StreamingAssets/Images/Furniture/RTG.xml, Assets/StreamingAssets/Images/Furniture/RTG.xml.meta, Assets/StreamingAssets/LUA/Furniture.lua
It is a power source and heater in one. The idea being it will never be as good as a stand alone heater or power generator. Current image is a place holder til someone one can make one fitting our style.
=> Adds Radioisotope Thermoelectric Generator - RTG

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/QuestController.cs, Assets/Scripts/Controllers/TradeController.cs, Assets/Scripts/Models/Quest/Quest.cs, Assets/Scripts/Models/Quest/QuestGoal.cs, Assets/Scripts/Models/Quest/QuestReward.cs, Assets/Scripts/Models/Trade/Trade.cs, Assets/Scripts/Models/Trade/TradeItem.cs, Assets/Scripts/Models/Trade/Trader.cs, Assets/Scripts/Models/Trade/TraderPotentialInventory.cs, Assets/Scripts/Models/Trade/TraderPrototype.cs, Assets/Scripts/UI/DialogBox/DialogBoxManager.cs, Assets/Scripts/UI/HeadlineController.cs
=> Some doc to trader, fixing style issues & stylecop issues

Assets/Resources/UI/DB_AreYouSure.prefab, Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxLoadGame.cs, Assets/Scripts/UI/DialogBox/YesNo/DialogBoxAreYouSure.cs, Assets/Scripts/UI/DialogBox/YesNo/DialogBoxResult.cs, Assets/Scripts/UI/DialogBox/YesNo/DialogBoxResult.cs.meta
=> Fixes #1025 DialogBoxAreYouSure not working anymore

README.md
Updated the game image to one more recent
=> Updating the Readme image

Assets/Scripts/UI/Overlay/OverlayMap.cs
=> Fixed typo "Currently Slected"

Assets/Scripts/Models/Power.meta
The power.cs.meta file was added in #1158 without having an associated power.cs file. Deleting this meta file that currently isn't needed.
=> Deletes the unneeded Power.meta file.

CONTRIBUTING.md
=> Fixes stylecop violations in CONTRIBUTING.md

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Models/Animation/FurnitureAnimation.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Power.meta
See excellent bug description in #1198.
=> Fixes #1198 - Furniture GetSpriteName also checks animation for a sprite

Assets/Resources/UI/DB_Settings.prefab, Assets/Resources/UI/DB_Settings.prefab.meta, Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs, Assets/Scripts/Utilities/Settings.cs, Assets/StreamingAssets/Settings/Settings.xml, ProjectSettings/QualitySettings.asset
The game is now set to no antialias, as explained in #1213
close #1213
=> Disable antialias

Assets/Scripts/Controllers/SpawnInventoryController.cs
Now we can pick an amount of inventory spawned when using the developer spawn inventory dialog
=> Spawn inventory dev. dialog now allows to pick quantity

Assets/Scripts/Controllers/KeyboardManager.cs, Assets/Scripts/Controllers/WorldController.cs
Add the possibility to active/desactive dev mode with F12
=> F12 dev mode

Assets/Scripts/Controllers/TradeController.cs, Assets/Scripts/Models/Prototypes/TraderPrototypes.cs, Assets/Scripts/Models/Trade/Trade.cs, Assets/Scripts/Models/Trade/TradeItem.cs, Assets/Scripts/Models/Trade/TraderPotentialInventory.cs, Assets/Scripts/Models/Trade/TraderPrototype.cs, Assets/Scripts/UI/DialogBox/Trade/DialogBoxTradeItem.cs, Assets/StreamingAssets/Data/Trader.xml
Same with Furniture and the other classes. ObjectType in Trader is now just Type.
=> Renamed ObjectType to Type in Trader

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/SoundController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/Prototypes/FurniturePrototypes.cs, Assets/Scripts/Models/Trade/Trader.cs, Assets/Scripts/Models/World.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/UI/CursorInfoDisplay.cs, Assets/Scripts/UI/MouseCursor.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/Data/Quest.xml, Assets/StreamingAssets/LUA/Furniture.lua, Assets/StreamingAssets/LUA/Quest.lua, CONTRIBUTING.md
We recently started changing to Type in other classes: Inventory, Stats, Needs... If we standardize on Type for all the classes that use the PrototypeManager I can simplify it by using an interface.
=> Renamed ObjectType to Type in Furniture

Assets/Scripts/Controllers/WorldController.cs
Fixes violations of SA1515 and SA1005 in `WorldController.cs`.
=> [tiny] Stylecoppage

Assets/Scripts/Models/Character.cs
This was missed during the Stats refactoring.
=> [Tiny] fixed character stats reading

Assets/Scripts/Controllers/ModsManager.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/CharacterNameManager.cs, Assets/Scripts/Models/CharacterNameManager.cs.meta, Assets/Scripts/Models/World.cs
I moved the loading of the character names into a new CharacterNameManager, from where you can get new names.
When loading names they are randomized and added to an unused names queue. Each time you ask for a new name, it retrieves the first from the list. This makes it so that you don't get repeated names, until all the names are used, and we start using all the used names again.
This also makes it possible for a mod to add its own names.
=> New CharacterNameManager

Assets/Scripts/Controllers/CharacterSpriteController.cs, Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Controllers/JobSpriteController.cs, Assets/Scripts/Controllers/ModsManager.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Controllers/SpriteManager.cs, Assets/Scripts/Controllers/TileSpriteController.cs, Assets/Scripts/Controllers/TradeController.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/Animation/CharacterAnimation.cs, Assets/Scripts/Models/Animation/FurnitureAnimation.cs, Assets/Scripts/Models/Inventory.meta, Assets/Scripts/UI/DialogBox/Job List.meta, Assets/_SCENE_.unity
A bit of refactoring over the SpriteManager class.
=> Sprite manager refactoring

Assets/Scripts/Controllers/MouseController.cs
This change avoids going out of build mode if we're panning. Very annoying if you're playing the game.
=> Added check for mouse panning

Assets/Scripts/Models/Inventory.meta, Assets/Scripts/UI/DialogBox/Job List.meta
PR #1280 added unwanted meta files. This PR removes them.
=> Remove unwanted metas

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Models/World.cs
Removed some unused code in World.
=> Removed unused code

Assets/Resources/Prefab/Button - Build Furniture.prefab, Assets/Resources/UI/MenuBottom.prefab, Assets/Resources/UI/MenuButton.prefab
I have just replaced the images of the buttom menu with @alexfriesen's ones and switching the font color to white.
=> UI Bottom menu images

Assets/Resources/UI/MenuRight.prefab
Another suggestion for temporary better.
I've used the menu construction background image.
=> UI Right Menu background

Assets/Editor/WorkshopTest.cs, Assets/Scripts/Models/FurnitureWorkshop.cs, Assets/Scripts/Models/State.meta, Assets/StreamingAssets/Data/Furniture.xml
Furniture that is workshop now supports animations. (animation for metal furnace for now)
=> Animations support for workshops

ProjectSettings/EditorSettings.asset
As the title says, add the lua files to the auto-generation of the solution/project by the vs studio extension of Unity.
Note:
To anyone using this and VS 2013, I suggest you adding a VS extension to color the lua code and have auto completion (for instance https://visualstudiogallery.msdn.microsoft.com/7782dc20-924a-4726-8656-d876cdbb3417)
=> Add lua files to the auto-generated solution/project files

Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
Fixes the issue when you change the Mining Drone to mine Raw Copper you get a non existent inventory.
=> The Mining Drone can now properly produce Raw Copper

Assets/Scripts/UI/Overlay/OverlayMap.cs, Assets/_SCENE_.unity
Few changes for adjusting position and color of overlay menu.
This need to be redone but just small adjustments waiting for that.
=> UI adjusting position and color of overlay menu

Assets/Scripts/Models/Prototypes/PrototypeMap.cs
Removing that space will fix the parsing error for Stylecop
=> Workaround for Stylecop Error

Assets/UberLogger/Editor/UberLoggerEditorWindow.cs
Reduces channel button clutter for UberLogger by changing the Grid Selection for channel buttons to use Popup instead(drop down menu). Discussed in #941
=> [Small] Changed UberLogger Channel Button to Dropdown

Assets/StreamingAssets/Data/CharacterNames.txt
Updates the character names to include the latest contributors. Welcome Alexfriesen, Buggy213, Rafaeu749, and Yurgeta!
=> Character name update

Assets/Scripts/Controllers/CameraController.cs, Assets/Scripts/Controllers/KeyboardManager.cs
=> [Tiny ]Small refactoring

Assets/Resources/UI/MenuLeft/ConstructionMenu.prefab, Assets/Scripts/Controllers/KeyboardManager.cs, Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
> Just because I'm blind with these kind of list
=> Add filter to construction menu

Assets/Scripts/Localization/LocalizationTable.cs
This change avoid loading all languages in memory.
=> Localization : Restrict the load to default and current languages

Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs
Will not work in the editor
you need to Build & Run to test
=> Toggle full screen in option menu

Assets/Editor/UnitTests/Models/FurnitureWorkshopTest.cs
using StringWriter/Reader instead of TextWriter/Reader (.xml only in memory)
fix for #1344
=> [small] FurnitureWorkshopTest not de/serializing to disk anymore

Assets/Scripts/Controllers/WorldController.cs
@sboigelot Here it is. I was going to add it to another PR, but I broke the loading somehow and I am looking why. So it is in its own PR now.
=> Removed old loading code

Assets/Scripts/Controllers/Sprites/CharacterSpriteController.cs, Assets/Scripts/Controllers/Sprites/JobSpriteController.cs, Assets/Scripts/Models/Character/CharacterManager.cs, Assets/Scripts/UI/DialogBox/JobList/DialogBoxJobList.cs
Which is much cleaner than having a getter that returns an array.
=> Character Manager now implements IEnumerable

Assets/Resources/UI/DB_Settings.prefab
=> Adapt the look of the Settings menu

Assets/Scripts/Models/Area/Room.cs, Assets/Scripts/Models/Area/RoomManager.cs, Assets/Scripts/Models/Area/RoomManager.cs.meta, Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Pathfinding/Path_RoomGraph.cs, Assets/Scripts/UI/MouseOverRoomDetails.cs
I believe that this is now as complete as I can imagine it. At least until @vogonistic gives some insight into how the `Joined` event should behave. But it should be ok to merge now, and change later if any of the functionality needs to be altered.
=> RoomEvents as per #1071

Assets/StreamingAssets/Data/CharacterNames.txt
Adding people from the Localization repository. Welcome Web-Flow!
=> Character name updates

Assets/Resources/UI/DB_Settings.prefab
It was using the wrong sprite before. Fixed now.
=> Fixed the hover states in the Settings Dialog buttons

Assets/Scripts/Localization/LocalizationDownloader.cs
=> LocalizationDownloader fix

Assets/Resources/Prefab/ContextMenuItem.prefab, Assets/Resources/UI/ContextMenu.prefab, Assets/Resources/UI/ContextMenu.prefab.meta
=> [Small] Fix for context menu width

Assets/Resources/UI/MenuLeft/ConstructionMenu/Button.prefab, Assets/StreamingAssets/Localization/en_US.lang
=> [Tiny] Fix for empty localization key in construction menu

Assets/Scripts/Localization/TextLocalizer.cs
I added a simple fix to fix an issue that has been addressed in #1425.
=> [Tiny] Fixing TextLocalizer

CONTRIBUTING.md
changes WIP and discussion tags to align to our current system. Also makes refrence to uberlogger.
=> Update PR tags and Logging Practices in Contributing.md

Assets/Scripts/Controllers/Sprites/CharacterSpriteController.cs, Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Models/Job/Job.cs, Assets/Scripts/Pathfinding/Path_TileGraph.cs, Assets/Scripts/Pathfinding/Pathfinder.cs
It's not absolutely perfect, but Crew can now navigate Z-Levels, and will work tiles directly above or below them. 
Thanks to @vogonistic and pderuiter(on discord) for the assistance that lead to getting this working.
=> [Feedback] 3d pathfinding

README.md
new recent screenshot from master for title page..
=> [Wiki] New screenshot (0.1-alpha)

Assets/Editor/UnitTests/Models/SchedulerEditorTest.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Events/GameEvent.cs, Assets/Scripts/Models/Events/GameEventManager.cs, Assets/Scripts/Models/InputOutput/ModsManager.cs, Assets/Scripts/Models/Job/JobQueue.cs, Assets/Scripts/Models/Prototypes/PrototypeManager.cs, Assets/Scripts/Models/Scheduler/Scheduler.cs, Assets/StreamingAssets/Data/Events.xml, Assets/StreamingAssets/Data/GameEvents.xml, Assets/StreamingAssets/Data/GameEvents.xml.meta, Assets/StreamingAssets/Data/SheduledEvents.xml, Assets/StreamingAssets/Data/SheduledEvents.xml.meta, Assets/StreamingAssets/GameEvents.meta, Assets/StreamingAssets/LUA/GameEvent.lua, Assets/_SCENE_.unity
The Game Events now use the Prototype Manager and the Game Events Manager is now an instanced created in World and updated through World.
Fixes #1451.
=> Game Events Manager Update

.mailmap
As reported in #1472, a number of people have committed under multiple
names/email addresses. This splits their contributions as reported by 'git
shortlog'.
The .mailmap file fixes the issue as can be checked by running
`git shortlog -sn | wc -l` which should return the current number of
contributors, i.e. 105.
It also allows people to change the formatting of their name, if desired,
in the shortlog stats.
The current output of `git shortlog -sn` is now
```sh
56	Koosemose
53	Martin "quill18" Glaude
45	Randshot
44	mikejbrown
39	kd7uiy
37	Tom├ís Malbr├ín
31	sboigelot
30	Gleb
21	Brian Jubelirer
21	Zak
20	Kent Karlsson
20	Ohda
19	Alexander Fast
18	Dormanil
16	Oscar Sommerbo
15	Simon Larsen
14	Julius H├ñger
13	James
13	dusho
12	Steve
12	Tymoteusz Adamczyk
12	jaselito
9	TRBRY
9	abackwood
9 …
```
=> Adds a .mailmap file to fix names & emails in git shortlog

Assets/StreamingAssets/Data/CharacterNames.txt
=> Update the character names list

Assets/Scripts/Localization/LocalizationTable.cs
=> Update Localization when Saving

Assets/Resources/UI/DB_Settings.prefab, Assets/Scripts/Models/Area/Room.cs, Assets/Scripts/Models/Area/Temperature.cs, Assets/StreamingAssets/Audio/Sound/OnCreated.meta, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
Fixes #1541 
Closes #1541 
Previously the temperature scaled infinitely. This fixes the code that caused this and added a check to prevent it from accidentally occurring in the future.
Also balances the flow of heat throughout the ship.
=> [Fix] Heat Rising Infinitely Fix

Assets/Resources/Prefab.meta, Assets/Resources/UI/DB_Trade.prefab, Assets/StreamingAssets/Audio/Sound/OnCreated.meta
Several Metas were left over from deleted/moved files, along with a few broken prefab connections. This reconnects
=> [Small, Fix] Delete Metas, reconnect more prefabs

.gitignore, ProjectSettings/ProjectSettings.asset
Per discussion in #1488 this readds ProjectSettings.Asset, which will allow us to set build version, Company Name, Application Name, Game Icon, and api compatibility level.
=> Readd ProjectSettings.Asset

Assets/Scripts/Pathfinding/Path_TileGraph.cs
A 3 line fix and I still let a stylecop error slip through... *sigh*
=> Stylecop 1579

ProjectSettings/EditorBuildSettings.asset
Looks like i forget this when i change the scenes location in #1564.
The paths was still on the old scenes location.
=> [Small][Fix] Update EditorBuildSettings with new scenes path

Assets/Scripts/Models/Settings.cs, Assets/StreamingAssets/Settings/Settings.json, Assets/StreamingAssets/Settings/Settings.json.meta
Settings.cs now uses json rather than xml as was decided in #1034
=> Converts Settings.cs to use json

Assets/_Scenes_/_World.unity
ContextMenuItem got disconnected from ContextMenu again
=> [Fix] Reconnect ContextMenuItem to ContextMenu

Assets/Scripts/UI/MouseOver.cs, Assets/Scripts/UI/MouseOver.cs.meta, Assets/Scripts/UI/MouseOverFurnitureTypeText.cs, Assets/Scripts/UI/MouseOverRoomDetails.cs, Assets/Scripts/UI/MouseOverRoomIndexText.cs, Assets/Scripts/UI/MouseOverTileTypeText.cs
adds abstract class MouseOver, all other MouseOver____ classes inherit from this class. The MouseOver____ classes only responsible for creating a string based of a tile. The MouseOver class deals with obtaining the current tile and setting the text component.
based on issue #1588
=> Remove duplicate code from MouseOver____ classes

Assets/Scripts/Models/Area/Room.cs, Assets/Scripts/Models/Area/RoomBehavior.cs, Assets/Scripts/Models/Area/RoomManager.cs, Assets/Scripts/Models/Area/World.cs
Currently Room Behaviors aren't saved.
This PR saves and loads them.
=> Save room behaviors

Assets/Scripts/UI/MouseOverFurnitureTypeText.cs
Minor change in the summary of the class.
=> Update MouseOverFurnitureTypeText.cs class summary.

Assets/StreamingAssets/Data/Quest.xml
Small fix changing quest.xml to match new furniture types.
=> Update furniture types in Quest.xml

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/Controllers/Sprites/FurnitureSpriteController.cs, Assets/Scripts/Controllers/Sprites/InventorySpriteController.cs, Assets/Scripts/Controllers/Sprites/JobSpriteController.cs, Assets/Scripts/Controllers/Sprites/UtilitySpriteController.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Buildable/Tile.cs
Simply cleaning up some of the TODOs that are either no longer accurate, or have been done, just trying to keep things as clean as possible.
=> TODO Cleanup

Assets/_Scenes_/MainMenu.unity, Assets/_Scenes_/_World.unity
Idk what else to say, it used to 'burn' images into the game cause it was on depth for clear flags.  Now it is on Skybox (no visual change whatsoever), and it doesn't.
This took so long to debug...  Thanks to @koosemose and sweat and blood :P.  We got there.
=> Fixes screen burning on Main Menu

Assets/Scripts/Models/InputOutput/AudioManager.cs
An old debug statement slipped in, just removing that.
=> Remove old Debug statement

Assets/Scripts/Models/Character/CharacterManager.cs
While fixing loading a character with inventory, I broke loading a character without inventory... whoops.
=> Fix loading character without inventory

Assets/Scripts/Models/OrderActions/Build.cs, Assets/Scripts/Models/OrderActions/Deconstruct.cs, Assets/Scripts/Models/OrderActions/Mine.cs, Assets/Scripts/Models/OrderActions/OrderAction.cs
Added Initialize method with possible initialization of JobInfo (if not deserialized)
Fixes # 1689
Closes #1689
=> Fix building a stockpile

README.md
Fixes date of migration being January the 1st of 2016 from PR #1709
=> Corrected migration date

CONTRIBUTING.md
Changed Uberlogger to UnityDebugger in CONTRIBUTING.md due to #1653
=> Changed Uberlogger to UnityDebugger

README.md
Changed 'are currently migrating' to 'may soon migrate'. Was going to put this in #1710 but it was committed before I could
=> Migration correction

Assets/Scripts/Models/Inventory/Inventory.cs
Accidentally left some unchanneled debug logs in the Inventory claim system... removing them.
=> Removed unneeded claim Debugging

Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/Data/Utility.xml
Overlooked inventory names in furniture.xml and utility.xml when I changed the names to be more consistent with the style used elsewhere.
=> Fix inventory names in furniture.xml and utility.xml

Assets/Resources/UI/DialogBoxes/DB_NewGame.prefab, Assets/Scripts/Controllers/SceneController.cs, Assets/Scripts/Models/Area/World.cs, Assets/Scripts/UI/DialogBox/DialogBoxNewGame.cs
This PR adds the ability to type in the seed before the game starts. please test for bugs. I style copped the code and there are no violations.
=> Adds a seed option to the new game screen

Assets/Scripts/UI/DialogBox/DialogBox.cs
removes an unneeded local version of Closed in DialogBox class
=> [small] Remove unnesscary local variable

Assets/Resources/UI/MenuTop.prefab, Assets/Resources/UI/TextPerformanceComponentUI.prefab, Assets/Scripts/Models/Trade/Trade.cs, Assets/Scripts/Models/Trade/Wallet.cs, Assets/Scripts/UI/InGameUI/MenuTop.meta, Assets/Scripts/UI/InGameUI/MenuTop/CurrencyDisplay.cs, Assets/Scripts/UI/InGameUI/MenuTop/CurrencyDisplay.cs.meta, Assets/Scripts/UI/InGameUI/PerformanceHUD/PerformanceHUDManager.cs, Assets/_Scenes_/_World.unity, ProjectSettings/ProjectSettings.asset, ProjectSettings/TagManager.asset
See #1075 
This PR adds a little textbox to the UI in order to display the amount of any given currency a player has.
=> Money counter

Assets/Scripts/Models/Functions/Parameter.cs, Assets/Scripts/Models/Settings/Settings.cs, Assets/Scripts/Models/Time/TimeManager.cs, Assets/Scripts/UI/InGameUI/PerformanceHUD/BasePerformanceHUDElement.cs, Assets/Scripts/UI/InGameUI/PerformanceHUD/PerformanceGroup.cs, Assets/Scripts/UI/InGameUI/PerformanceHUD/PerformanceHUDManager.cs, Assets/Scripts/UI/InGameUI/SettingsMenu/BaseSettingsElement.cs, Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsCategory.cs, Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs, Assets/Scripts/UI/InGameUI/UIElements/BaseUIElement.cs, Assets/StreamingAssets/CSharp/PerformanceHUDFunctions.cs, Assets/StreamingAssets/CSharp/SettingsMenuFunctions.cs, Assets/StreamingAssets/Data/PerformanceHUDTemplate.xml, Assets/StreamingAssets/Data/SettingsTemplate.xml, ProjectSettings/ProjectSettings.asset
**Note: only touches the code side shouldn't have any influence on the visual appearance**
This is not only for settings menu options, this is for all systems that use my UI system (currently just settings menu and performance HUD but hopefully it'll expand :P), it now uses a more code based approach.  This is done through adding support for custom parameters, you just define them like every other parameter in xml (like furniture ones it uses same class), but then you can access those paramters and use them to implement custom settings.  
Note this is all done soft coded, even the 'generic' methods are staying as a core mod they aren't hardcoded into the game, I wanted to keep it this way not only as a good example of how to code for the settings menu but also to push the game as mostly a …
=> Custom Parameter support for my UI System

README.md
Self explanatory just removes the migrating notice from the readme.
=> [Small] Remove the migrating notice
