TeamPorcupine/ProjectPorcupine

README.md
The link to the workflow tutorial video on Youtube was missing.
This commit adds it to the contributing section.
=> Add link to video tutorial on youtube

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Data/Furniture.xml, README.md
I added the ability to inset furniture in place of other furniture. Details below for a `Door` into `Wall`example
For example, a `Door` needs to be able to replace a `Wall` so in the XML on the Door furniture, I'll add this line.
ie. `<CanReplaceFurniture objectName="Basic Wall" />`
Now validation will allow me to replace a wall block with a door.
**Note**: I apologise for all the unnecessary file changes. My MonoDevelop added auto-formatting to some of the methods.
=> Allow certain furniture to replace other furniture - ie. Doors into Walls

.gitattributes
Without this everyone who contributed could push his own line-endings to repository leading to destroying of the universe... Or some annoying Unity warnings.
=> Ensure that git sets text files to OS-native EOL

Assets/Scripts/Controllers/JobSpriteController.cs
Since floors require the player to build them I decided to add in the preview sprite. Unfortunately since the job system isn't fleshed out yet, the approach is a bit hackish. However, it works perfectly fine and can easily be updated once the job system is redone (specifically the job sprite system)
=> Add preview for building floors

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/Models/Character.cs
Some leftover debug code from testing features is filling the debug log with hundreds of messages. This addresses #94
=> Remove log spam

Assets/StreamingAssets/Data/Furniture.xml
**BuildingJobs for every furniture so their furniture job prototypes get initialized.**
I noticed that every time I place any other furniture than Door or Wall I get an error like:
`There is no furniture job prototype for 'Mining Drone Station'.`
Reason for that was missing BuildingJob tags for other furniture.
So I added the BuildingJob tags with jobTime 0 in those furniture and now the error is gone.
=> BuildingJobs for every furniture.

Assets/Scripts/Models/Job.cs
Whenever the jobTileType variable was added to the Job class for tile construction jobs, the copy constructor wasn't updated.
=> Add jobTileType to job copy constructor

Assets/Scripts/Controllers/WorldController.cs
An out of bounds error would be thrown when attempting to increase the time scale beond the maximum allowed amount, due to an off-by-one error.
=> Fix off by one error with time scale

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/UI/MouseOverFurnitureTypeText.cs, Assets/Scripts/UI/MouseOverRoomIndexText.cs, Assets/Scripts/UI/MouseOverTileTypeText.cs
This bug is triggered if you try to build a base in a new game. The conditions are:
- Building in open space
- There is no stacks of steel on the ground (I have a mining droid, but it doesn't change anything)
- The character tries to build a wall
`GetPathToClosestInventoryOfType` will trigger a search that can't find anything and do so on the entire map. It is very, very slow to search all 10k tiles.
The fix assumes that `InventoryManager` knows about all stacks on the floor, which is true according to my testing. It now verifies that there is a stack to find before starting the search. To help make it a little easier to follow, it's also broken into several checks with individual comments.
I also included two misc bug fixes that I got errors for while trying to figure out why my game …
=> Avoid full map search for items that doesn't exist

Assets/Scripts/Utilities/Logger.cs, Assets/Scripts/Utilities/Logger.cs.meta
This was discussed in #94.
I've made the methods look like the ones already in Unity so that you can simply swap anywhere it says `Debug.LogError()` to say `Logger.LogError()` and all its variants. 
It has a minimum level that defaults to `Info`, only that level and more severe levels are logged. This means by default the level `Verbose` is hidden.
Verbose is the only new "level" compared to what Unity has. It's intended for everyone to go completely nuts with logging here. Since its hidden by default it wont affect anyone and should only be enabled when developing or debugging. This addresses the concerns with how much you are allowed to log, and how much of your debugging logging you should strip out when you make a pull request.
There is a neat trick to using this that might not be …
=> Added custom logging class wrapping unity logger.

Assets/Scripts/Models/Tile.cs, Assets/StreamingAssets/Localization/en_US.lang
When selecting a tile (empty or floor), no localization support was present for the selection dialog.
=> Added localization support for tiles

.gitattributes
Attempts to fix some end-of-line issues that were causing problems for everyone.
=> Tell .gitattributes that .txt files are text.

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Pathfinding/Path_AStar.cs
The character should walk to the tile, but stop beside it rather than on it.
This currently only happens when constructing floors.
Implemented by essentially removing the last tile from the found path.
=> Added support for executing jobs on an adjacent tile.

Assets/Scripts/Models/Character.cs
There are a number of common logging functions that slow things down drastically. These are switched to Verbose, so they normally don't show unless requested.
=> Change several very common logs to Verbose to reduce log spam

Assets/StreamingAssets/LUA/Furniture.lua
Metal Smelter needs to include a priority. Set it at medium.
=> Make Metal Smelter consistent with new Job prototype

Assets/UI/DialogListItem.cs
Delete button does not show in the save dialog. By design or by mistake of #194. I added a quick fix to check if GO is found. A proper refactor of the delete button might be in order.
=> Fixed bug in save dialog from the delete button

Assets/Scripts/Models/WorldGenerator.cs
This changes the world generation to now generate raw iron, which added in #245, instead of steel plates.
As such, this depends on #245.
=> Raw Iron WorldGen

Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Data/Furniture.xml
Per further discussion in #31, BaseType was changed to TypeTag (to more closely match new functionality), and now allows multiples (previously it would be set to the last one found). Added bool HasTypeTag(String) method to separate usage from implementation (future-proofing for any potential changes in the future).
=> Change BaseType to TypeTag, and allow multiples

Assets/Scripts/Localization/LocalizationTable.cs
As discussed in #247.
Now in hindsight this turned out rather simple and maybe I should have left it for a beginners task. But it does increase performance by not spamming log with the same message.
=> Missing localization keys are now only logged once.

Assets/Scripts/Controllers/BuildModeController.cs
If you had a bunch of jobs, you could not remove any of the designations
=> Added functionality to remove the designation of furniture

Assets/StreamingAssets/Data/Furniture.xml
Fixes #303.
Ability to upgrade doors to Airlocks is added.
=> Issue #303 - Allow Airlocks to replace Doors

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/StreamingAssets/LUA/Furniture.lua
I added the ability for inventories to be "locked". This basically means that inventories that are locked can't be picked up for completing jobs. This is a fix for #339.
=> Lock inventory

CONTRIBUTING.md
Just copy pasted commands to my terminal and noticed at line 17 there was an typo.
This PR fixes that typo get -> git.
=> Fixed typo get -> git in CONTRIBUTING.md

Assets/Scripts/Controllers/MouseController.cs
A fix for #393. I always thought that it was a good idea to disable scrolling while over ui.
=> Disable scrolling over ui-elements

Assets/Scripts/UI/MenuController.cs, Assets/_SCENE_.unity
Issue:  the construction menu has buttons for furniture and floor which yield more buttons when clicked. However, when you click furniture again, the furniture buttons don't go away.
Fix: turned furniture and floor buttons into toggles so their menus can be hidden by pressing them again
note: this required scene modification to change the buttons OnClick targets
=> made construction buttons toggles

CONTRIBUTING.md
Current link is broken and leading to this:
I fixed it to the real link.
=> Fixed link to video tutorial in CONTRIBUTING.md

Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/Pathfinding/PathfindingPriorityQueue.cs, Assets/Scripts/Pathfinding/PathfindingPriorityQueue.cs.meta
While looking through the pathfinding code, I discovered that the SimplePriorityQueue being used by the pathfinding system has worst-case O(n) Contains and UpdatePriority, both of which are used frequently by the pathfinding system (resulting in a worst-case O(n^2) algorithm, at least in theory). FastPriorityQueue has O(1) Contains and O(log n) UpdatePriority, but the process of wrapping SimplePriorityQueue around it introduces a fair amount of overhead. So I wrote a variant of the SimplePriorityQueue class that uses Dictionaries to speed things up a bit. Pathfinding is still a bottleneck, but hopefully this can make the neck a little wider?
I also removed the lines initializing all of the f_scores and g_scores, since the process that the algorithm goes through adds f_scores and g_scores …
=> A few pathfinding tweaks to increase efficiency a little bit.

Assets/Scripts/Models/Tile.cs
The character will only walk on floors and empty tiles that have at least one floor tile adjacent to them.
This was the easiest way I could think of to still allow placing floors.
This does mean the character will still 'jump' over gaps up to 2 tiles wide.
=> Restricting character movement to floors.

Settings.StyleCop
Specifically SA1633 and SA1635.
Now that #287 has been merged.
Maybe one day the list of deviations in this file will reach zero. :)
=> Enabled StyleCop rule enforcing file headers.

Assets/Scripts/Controllers/CharacterSpriteController.cs
I don't like that characters are being given names in the Sprite Controller (seems like it should be part of the model instead), but in any case this particular fix needs to happen regardless of where we put the file.
=> Fixed newline splitting to deal with both CRLF and LF

.gitignore, Assets/Scripts/Controllers/ModsManager.cs, Assets/Scripts/Controllers/ModsManager.cs.meta, Assets/Scripts/Controllers/SpriteManager.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Models/World.cs, Assets/StreamingAssets/Data/Mods.meta, Assets/StreamingAssets/Data/Mods/README.md
Did not plan this but it worked out, so I am very sorry if some one is working on it already.
This is a simple way to load mods.
Currently only loads furniture (xml, lua, and sprites) form `/Assets/StreamingAssets/Data/Mods`.
At some point I would like to add a Mod Manager that will Install and update mods (probably from GitHub)
=> Modding managment

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Models/GameEvent.cs, Assets/Scripts/Models/GameEventActions.cs, Assets/Scripts/Models/ISelectable.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryManager.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/JobQueue.cs, Assets/Scripts/Models/PowerSystem.cs, Assets/Scripts/Models/Room.cs, Assets/Scripts/Models/WorldGenerator.cs
Improved Style of scripts in the models directory. 
Did not rename methods/Varibles or reorder public/private
=> StyleCoped scripts/models/*.cs

Settings.StyleCop
Heres a case where I think StyleCop is trying too much. The rationale is that space between code increases readability by decreasing clutter.
> SA1503 : CSharp.Layout : The body of the if statement must be wrapped in opening and closing curly brackets.
if (i < 0 || i > rooms.Count - 1)
return 
return rooms[i]; // not good
But doing the obvious is not enough because then another rule pops up.
> SA1513 : CSharp.Layout : Statements or elements wrapped in curly brackets must be followed by a blank line.
if (i < 0 || i > rooms.Count - 1)
{
return null;
}
return rooms[i]; // not good either
So it wants this:
if (i < 0 || i > rooms.Count - 1)
{
return null;
}
return rooms[i];
I think both rules tries to address the same problem in the same place. And it results in a double dip, a tad too much.
I …
=> Disabled StyleCop SA1513

CONTRIBUTING.md
Quill released a revised YouTube video for the Git, GitHub, and Unity. However, the link was not yet updated, so I figured I'd contribute a quick update.
=> Update Git Tutorial YouTube Link

Assets/Scripts/Localization/LocalizationLoader.cs
currently localization spams each lang file to the log on start. Changed so that this only occurs in verbose mode.
Bonus: added space to preceding comment
=> [Small] Make 'Loaded localization' log message LogVerbose

Assets/Scripts/Controllers/TileSpriteController.cs
OnTileTypeChanged was renamed to OnTileChanged. I just fixed a reference to that old method name in the error logging, because I couldn't find that method when I got the error message.
=> [Small] Fixed an error message that contained old method name.

Assets/Scripts/UI/MouseOverFurnitureTypeText.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/Localization/en_US.lang
Fix https://github.com/TeamPorcupine/ProjectPorcupine/issues/507
Don't include the tag if there isn't furniture (As shown above)
Steel Wall has the tool tip "basic wall". That seems off.
=> Furniture tab tooltip #507

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Tile.cs
This removes the need to make a full A* to find that the tile is not accessible.
=> Added small accessability check before pathfinding

Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/InventoryCommon.cs, Assets/Scripts/Models/InventoryCommon.cs.meta, Assets/Scripts/Models/World.cs, Assets/StreamingAssets/Data/Inventory.xml, Assets/StreamingAssets/Data/Inventory.xml.meta
You can already use it so that you do not have to write what the maxStack is. It is easily added uppon. In the world class there is now an inventoryPrototypes list that functions like the FurniturePrototypes. I will add upon this. Currently nothing uses it
I did not wan't to change everything to the new system yet as that would require to nearly change the whole lua file and merging that would be a pain so, i thought we can start with this and everyone can switch to the new system on their own...
=> Added the start of the new Inventory.xml

Settings.StyleCop
This reverts commit 3e3a8b4831108f79a9cddf9ae0824da8a8c4be24.
Reverts pull request #562. It got voted down but then got merged anyway. Mistakes happen, but this corrects that. :)
=> Revert "Disabled SA1513 ClosingCurlyBracketMustBeFollowedByBlankLine"

Assets/Scripts/Models/Job.cs
There was a problem with a lua function registering a callback which modified a currently enumerated list causing a enumeration modification error. This changes the iteration so that they iterate through a copy list.
=> Fixed enumeration modification error in cbJobCallbackComplete

CONTRIBUTING.md
I have updated CONTRIBUTING.md to include the new standard naming convention Inventory and Furniture. The rest of #505 I will be trying to recreate in a new pr.
=> New naming standard CONTRIBUTING.md

Assets/StreamingAssets/LUA/Furniture.lua
Hack to fix issue https://github.com/TeamPorcupine/ProjectPorcupine/issues/577 (correct me if this issue is about a slightly different bug! This fixes the only smelter weirdness I can reproduce.)
The problem is that the spawn spot inventory is disappearing so the smelting never gets started. I've just turned the smelter into a little finite state machine using a furniture param "smelting" as flag and manually resetting the spawn spot inventory. I'm sure there's a better way to fix this but it's working for now.
=> Fixing metal smelter bug issue #577 (with hacks)

Assets/Scripts/Pathfinding/Path_AStar.cs
I just realized that the pathfinding code is currently storing the Closed Set as a list. The only operation it's ever performing on that list is Contains, which is very slow (asymptotically O(n)) on CSharp's built-in list. This changes it to a dictionary, which can check containment much faster (close to O(1)).
I'm pretty sure this drastically speeds up pathfinding. I'll try to get my pathfinding tests working again so that I can actually give some hard numbers, but in the one test that I've managed to get working, it changed one of the searches from ~2.5s to ~0.25s.
EDIT: Thanks to a suggestion by @Mizipzor, I changed from a Dictionary to a HashSet. It's about the same speed, but it's more elegant. Also, I got the tests working again, with my results posted in the comments below. Eight …
=> [Pathfinding] Fixed slow ClosedSet contains queries.

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
This is my solution to make ```GetSpriteForFurniture``` to be less hard coded and is now posible to change the value for any furniture, mentioned in #657.
Eventually we might change this with a sprite animation manager, but for now this can be used for furniture animations.
=> Made GetSpriteForFurniture less hard coded

Assets/Scripts/Models/FurnitureActions.cs, Assets/Scripts/Utilities/ModUtils.cs, Assets/Scripts/Utilities/ModUtils.cs.meta, Assets/StreamingAssets/LUA/Furniture.lua
This is a replica of the previous modutils #37, without accidentally changing hundreds of files. I don't know if this is needed in the project, but the full discussion never got finished after I messed up that PR.
ModUtils exposes methods in c# by encapsulating them in methods within the ModUtils class. These can then be called in Lua with `ModUtils.MethodName()` and removes the need for a redundant "utilities" section in the Lua files, which was essentially for rewrites of existing c# functions, like `Mathf`.
Bonus: all changes are Style Cop compliant
=> ModUtils: Exposes static Unity C# functions to Lua

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Models/Furniture.cs, Assets/StreamingAssets/Images/Furniture/DoorHorizontal.xml, Assets/StreamingAssets/Images/Furniture/DoorHorizontal.xml.meta, Assets/StreamingAssets/Images/Furniture/DoorVertical.xml, Assets/StreamingAssets/Images/Furniture/DoorVertical.xml.meta, Assets/StreamingAssets/LUA/Furniture.lua
This replaces the old door sprites with the new ones created by @longtomjr
It adds a flag to the furniture (probably not the final solution!) that is then set by the `FurnitureSpriteController` instead of rotating the game object.
This is checked by the Lua code in `GetSpriteName_Door` to determine which sprite sheet to use.
`openness` still determines which sprite to use but now has a wider selection.
Includes the XML from #742 also created by @longtomjr
=> Door sprites updated

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Job.cs, Assets/StreamingAssets/LUA/Furniture.lua
Fixes #568 
This is still incomplete and could probably use a lot of refactoring. I'm putting it up to get feedback.
This PR implements any/all logic for stockpile type jobs. Jobs now have a `public bool acceptsAny` & material requirements can be checked in a unified way through the method `MaterialNeedsMet()` which calls `HasAllMaterial()` or `HasAnyMaterial()` as needed.
Character logic has been updated so that when working on an "any" job they will go pick up any reachable inventory listed in the Job's inventoryRequirements.
Furniture now has an `public Inventory[] AcceptsForStorage()` function which is hard coded for now for testing, but which will eventually be hooked up to stockpile UIs. The stockpile LUA has been updated to use this.
I'm thinking about implementing …
=> Fixing stockpile logic: implementing taking multiple inventory types and any/all logic

CONTRIBUTING.md
Adds:
> ~~You may also want to~~ It is also highly recommended that you install [StyleCop](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/StyleCop), which will automatically point out any deviations from the project's style guidelines.
to the bottom of the Style Guidelines
=> [Small] Add StyleCop wiki link in contributing.md

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Models/Room.cs
Fixes #685 
Note: need the fix for #639 to test this.
This fix affects deconstructing through the construction menu but not by the right click menu.
=> No longer deconstructs walls when this would cause depressurisation

Assets/Editor.meta, Assets/Editor/ParametersEditorTest.cs, Assets/Editor/ParametersEditorTest.cs.meta, Assets/Scripts/Models/Parameter.cs
It's good practice to start adding as much testing as possible. Here's a start on a particularly easy to test class: `Parameters`.
Uses Unity Editor tests based on NUnit. For those unfamiliar (assuming there are some newbies around) see the [Unity docs](https://docs.unity3d.com/Manual/testing-editortestsrunner.html) and [NUnit docs](http://www.nunit.org/index.php?p=quickStart&r=2.6.4). Run the tests in the Unity editor by going Window > Editor Tests Runner then clicking Run All.
Had to make some minor fixes to `Parameters` to get all the tests running. Some test(s) will have to be changed if #746 is merged.
From now on changes to the `Parameters` API can be spec'ed out in the tests in terms of the _expected_/_desired_ behavior, and _then_ the implementation coded to make the tests pass …
=> Added unit tests for Parameters

Assets/Scripts/Models/TileType.cs, Assets/Scripts/Models/World.cs, Assets/Scripts/Utilities/LuaUtilities.cs
This moves all the Lua file loading to a centralized function, which additionally wraps the loading in a try-catch block that outputs an informative message indicating which line of the file caused the problem.
=> Lua script file loading centralized with try-catch

Assets/Scripts/Utilities/LuaUtilities.cs
I haven't found a way to replace the unclear "chunk2" parts of these exceptions with Lua filenames, but in any case this includes a line number reference in the Moonsharp runtime errors that is very helpful for debugging.
=> Lua runtime exception handling

Assets/Editor/ParametersEditorTest.cs
Do as I say, kids, not as I do. #746 broke one of the tests by changing the spec (such as it is) as expected, so I rewrote the test. Also wrote a new test (already passing) checking behavior of Parameters which have a value as well as a sub-parameter.
Question: should Parameters override equality operators? It appears they compare by reference, not value as I would expect... There should be test coverage either way but I've held off because there isn't really a defined behavior yet. What do people want?
I could either put a [WIP] on this if you want to discuss it here or open an Issue and let this be merged for now.
=> Rewriting Parameter unit test to match implementation & increasing coverage

Assets/Scripts/Models/Room.cs, Assets/Scripts/Models/World.cs
There was a bug in the furniture deconstruction code that when a wall was deconstructed the surrounding walls where never deleted.
This just deletes the rooms before doing the flood fill however this won't preserve the gas calculations.
=> Room deletion

Assets/Scripts/Models/Character.cs
```
NullReferenceException: Object reference not set to an instance of an object
Character.OnInventoryCreated (Inventory) (at Assets/Scripts/Models/Character.cs:765)
World.OnInventoryCreated (Inventory) (at Assets/Scripts/Models/World.cs:1092)
InventoryManager.PlaceInventory (Tile,Inventory) (at Assets/Scripts/Models/InventoryManager.cs:71)
(wrapper dynamic-method) System.Runtime.CompilerServices.ExecutionScope.lambda_method (System.Runtime.CompilerServices.ExecutionScope,object,object[]) <IL 0x00035, 0x00150>
MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00049, 0x00231>
MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.PerformOverload …
```
=> Added check against null Object

Assets/Editor/PowerGridTest.cs, Assets/Editor/PowerSystemTest.cs, Assets/Scripts/Models/Power/Connection.cs, Assets/Scripts/Models/Power/Grid.cs, Assets/Scripts/Models/Power/System.cs
Next step would be use this system.
Add to `World` and `Furniture`
=> Live power system: fixed bugs and it is should be ready to use

Assets/Scripts/Controllers/BuildModeController.cs, Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/JobQueue.cs, Assets/Scripts/Models/TileType.cs, Assets/StreamingAssets/LUA/Furniture.lua
I put the JobPriority enum back into the Job class to make it accessible from Lua without having to define global replacements for them in the Lua files.
For this, I had to rename the JobPriority property to Priority.
**_I do think that this is an acceptable name for the property._**
**_If you think otherwise, then please explain why and maybe how to solve it differently._**
=> Put JobPriority enum into Job class

Assets/Scripts/Models/Character.cs
Needs set a null DestTile, which was causing a NullReferenceException When O2 level gets below 50%
=> Added null check to GetNewJob()

Assets/Scripts/Models/World.cs
Characters now have random colors by default and overloads utilize each other so that there's no code duplication. This also fixes characters that were being generated without a color not having a random name, since that function just calls the other overload with a random color.
=> Fix character-generation overloads

Assets/Scripts/Utilities/ModUtils.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
Airlock doors can now be pressure locked (only open when the pressure is equal on both sides, accurate to 3 decimals).
This currently doesn't do much as there is no way to change the pressure in a room other than to open doors, or otherwise put a hole in a wall, but is the first step to allowing airlock doors to be used to make a proper airlock.
Default is for them to not be pressure locked (toggled from context menu) so as to not create any difficulties in using airlock doors before some form of pressure pump is added. For now airlock doors will continue to behave as before, unless the pressure lock is toggled on, then in most cases they just won't open (since there is no way to change the pressure in a room).
To test, a hole can be made in an outside wall, to dump all the atmosphere, …
=> Allow airlock doors to be pressure locked

Assets/Scripts/Controllers/SpawnInventoryController.cs
It's possible to generate `NullReferenceException`s by clicking off the map in dev spawn mode. This just fixes that.
=> [small] Add null tile check to SpawnInventory

Assets/Scripts/Models/Prototypes/XmlPrototypes.cs, Assets/Scripts/Utilities/Settings.cs
`Settings.cs` fail StyleCop, needs rule change. StyleCop message: 
SA1305 : CSharp.Naming : The variable name 'xDoc' begins with a prefix that looks like Hungarian notation. Remove the prefix or add it to the list of allowed prefixes.
=> [Small]Cleaned up lingering Debug-calls. 

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/TileType.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/Pathfinding/Path_TileGraph.cs, Assets/StreamingAssets/Data/Furniture.xml
This is an extremely basic Pathfinding Weight for Tiles (which calls Furniture for it's pathfinding weight if it has furniture). At the moment the only thing used is movementCost, modifiers to the final weight (Accessed through the property PathfindingWeight on Tile), are set at 1. Pathfinding can get the total PathfindingCost (PathfindingWeight * movementCost) from the PathfindingCost Property.
The purpose is to get an extremely simple thing in place that allows those working on pathfinding to make use of a weight that can be further modified from movementCost, that is small enough to allow it to easily be merged. This will allow them to make use of it as soon as possible, and any further changes to how weight is calculated will be handled separately and should minimize conflicts with …
=> Implement PathfindingWeights

Assets/UberLogger/UberLogger.cs
Replaces newlines with space, UberLogger was supposed to work this way but wasn't due to `Enviroment.NewLine` wonkyness.
Added function that should handle both Unix and Windows, tested on windows.
=> Fixes multiline problem in UberLogger on all platforms I hope.

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Tile.cs
I have fixed the context menu in Furniture.cs where i had only shown the first job in the index(i know it was ugly and not good practice), now it will properly show all jobs that can manually prioritized by a selected character. Also in Tile.cs, for its context menu, i had hard coded the name of the job because at the time there was no good way to get the name. But now that jobs are selectable, i have changed it to show the name of the object that will be prioritized. 
Also in Furniture.cs, there was a foreach loop in the GetContextMenuActions() that used a 'var', i have removed the var.
NOTE: No in game change except for a pending build job showing its name in the context menu when a character is selected.
=> [Small] Fixed Furniture and Job context menu

Assets/Scripts/UI/InGameUI/ConstructionMenu.cs
#960 noted that their PR doesn't scale well. This aims to fix this by replacing repetitive `menu.SetActive(false)` calls with easier and clearer `DeactivateSubsExcept(selectedMenu)`.
While this changes very little now, a menu with five sub menus logic would be the followin in the current master inside each buttons delegate:
```
floorMenu.SetActive(false);
furnitureMenu.SetActive(false);
powerMenu.SetActive(false);
medicalMenu.SetActive(false);
```
This changes the logic to :
`DeactivateSubsExcept(miscMenu); `
=> Fix repetitive logic in ConstructionMenu

Assets/Scripts/Models/World.cs
Now that we have spawning of asteroids with resources, as well as mining furniture and ways to implement item gathering in-game, these debug resources can safely be removed and clean-up the code.
=> Remove debug items spawned on world load

Assets/StreamingAssets/LUA/Furniture.lua
fixes #973 
The lua code didn't properly access desiredItems as a table. The Metal Smelter will now only request enough items to fill it's stack, as originally intended. It also won't consume excess items if a character happens to have too many.
=> Fix metal smelter job construction

Assets/Editor/BuildGame.cs, Assets/Editor/BuildGame.cs.meta
This PR introduces the first step for continuous integration for #73: creating builds from the command line.
This is done via the following commands:
OSX/Linux/Unix:  `/Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -logfile -projectPath path/to/ProjectPorcupine -executeMethod BuildGame.OSX`
Windows:  `"C:\Program Files\Unity\Editor\Unity.exe" -quit -batchmode -logfile -projectPath path/to/ProjectPorcupine -executeMethod BuildGame.Windows`
You can change the build target by changing the method called in `BuildGame`. Currently there are options for Windows 32bit, Windows 64bit, MacOSX universal, Linux universal, and all at the same time.
=> Build From Command Line (for CI)

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Parameter.cs
This is a redo of PR #819 .
It fixes how Parameters are saved and loaded, and changes the save format of Parameters match how they are written in the furniture prototypes, allowing the same Loading code to handle both.
This fixes a bug where the parameters of furniture (and any other object that uses Parameters) weren't properly loaded on Load Game, causing most furniture that uses Parameters to not work on Load.
=> Fix param saving/loading

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Room.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Pathfinding/Path_TileGraph.cs
(Don't know if this bug has been reported yet.)
To reproduce the bug build floor tiles along the edge of the map. This fixes it.
=> [small] Always check against NullReferenceException when using tile.GetNeighbours!

Assets/Scripts/Controllers/FurnitureSpriteController.cs, Assets/Scripts/Controllers/InventorySpriteController.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/Models/World.cs
Removed TODO like this:
```
//FIXME:  What if we have a multi-tile furniture?
// TODO: This function assumes 1x1 tiles -- change this later!
```
We support multi-tile object. Or I am wrong?
=> Removed redundant TODOs

Assets/StreamingAssets/LUA/Furniture.lua
Fixes 'NullReferenceException: Object reference not set to an instance of an object` . When the metal smelter tries to spawn the steel plates it can't find the location. Variable was misspelled.
=> Fixes NullReferenceException in Metal Smelter

Scripts/test.sh
Test.sh now parses unity's log file from a failed build and repeats the console output at the end of the build for easy access to errors. 
Previously the compiler errors from a build were logged, but 300 lines above where the build actually reports failing, making finding errors very difficult.
Sample output of a failing build:
=> Show compile errors clearly in Travis CI

Scripts/test.sh
fixes the order of echos in travis so the log folds on headings rather than the line after
before:
After:
any messages about failures still are shown after the Unit Tests section and will not be folded.
=> Fix folding in Travis log

Scripts/test.sh
when a Travis build fails due to a unit test failing, Travis will now log the exact failure at the end of the build log.
here is a sample where two unit test fail:
https://travis-ci.org/bjubes/ProjectPorcupine/builds/157662489
=> Log failed unit tests to Travis CI

Assets/Scripts/Controllers/SpriteManager.cs
Set the FilterMode to Point for textures loaded in SpriteManager to make them look nicer (not washed out) when zoomed in.
PSA: I didn't change the default ppu for files without XML, because I honestly think that we should never have decided to do that, especially when everyone in favour of 32x32 (majority of the Sprite Crew on Discord) was not even there.
=> FilterMode Point for SpriteManager-loaded sprites

Assets/Scripts/Utilities/UnitTestDetector.cs, Assets/Scripts/Utilities/UnitTestDetector.cs.meta, Assets/UberLogger/UberLogger.cs
Some UnitTest are failing when running them from IDE (VisualStudio) with exception:
```
System.TypeInitializationException: initializer type "UberLogger.Logger" threw an exception.
  ----> System.Security.SecurityException: ECall methods must be packaged in a system module.
   in UberLogger.Logger.Log (String channel, Object source, LogSeverity severity, Object message, Object [] par)
   in Debug.ULogChannel (String channel, String message, Object [] par) in D: \ Development \ GitHubRepository \ ProjectPorcupine \ Assets \ UberLogger \ Debug.cs: line 127
   in ScheduledEventTest <Init> b__2_0 (ScheduledEvent evt) in D:. \ Development \ GitHubRepository \ ProjectPorcupine \ Assets \ Editor \ ScheduledEventTest.cs: line 26
   in Scheduler.ScheduledEvent.Fire () in D: \ Development \ …
```
=> UberLogger can detect that he called from Unit Tests

Assets/Editor/UnitTests/Models/Power/PowerGridTest.cs, Assets/Editor/UnitTests/Models/Power/PowerNetworkTest.cs
When unit tests have namespaces the unity editor gets ..weird
This removes the namespaces in the power unit tests.
^ much better :)
unfortunately, most of the changes git notices are fixing indentation, only 4 lines were actually modified
=> Remove Namespace From Unit Tests

Assets/Scripts/Models/Furniture.cs
Fixes #1161
When power is lost the jobsTimes would reset because the jobs were canceled. This new method takes the current jobs running and stores them in a new List until the power is restored then the jobs are added back to the normal job queue with any current work done to them saved.
=> Fixes #1161 - Jobtime reset after powerloss

Assets/StreamingAssets/LUA/Furniture.lua
`Furniture.cs` already has this check in `Update()`it before it calls the Lua `OnUpdate`
=> Removed redundant HasPower() call in Lua

Assets/Scripts/UI/FurnitureBuildMenu.cs, Assets/StreamingAssets/Data/Furniture.xml
This adds the ability to tag furniture with a `TypeTag` that stops it from showing up in the build menu, which checks before generating a button and moves on to the next furniture if it has the tag.
Currently this is only implemented on the mining points so that the player cannot build them, but will likely be used for most furniture objects created during world gen such as asteroid walls.
For the moment the tag is `Non-buildable` but I am not sure this is ideal and I am open to better suggestions.
I have also redone a bunch of names in the `FurnitureBuildMenu` to hopefully meet standards and to pre-empt any suggestions that they be changed to something else. Please point out if its to much or not correct so I know for the future. :+1:
=> Build Menu - Non-buildable furniture

Assets/Scripts/UI/HeadlineController.cs
This will prevent button clicks from being processed when the dialog is invisible.  Fix #1171
=> HeadlineController popup disabled when not visible

Assets/Scripts/UI/HeadlineController.cs
Headline scheduling events can get saved, and re-used, even though the UI element is gone. For the time being, checking to see if this appears to be one of those cases, and does nothing to prevent a crash. Fixes #1175
=> Fixes bug on load Headlines

Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs, Assets/Scripts/UI/FurnitureBuildMenu.cs
Reworked `FurnitureBuildMenu` to allow the furniture list to be rebuilt on the fly, this also allows for Dev mode to make all furniture visible/buildable regardless of Non-buildable flag.
You can call the `RebuildMenuButtons` function to rebuild the list and either tell it to display everything or just rebuild the list.
It should be fairly easy to expand on the checks to make certain buildings become visible when required or vice versa.
Any suggestions for changes welcome! :+1:
=> Rework of FurnitureBuildMenu

Assets/Scripts/Controllers/MouseController.cs, Assets/Scripts/UI/InGameUI/ConstructionMenu.cs, Assets/Scripts/UI/InGameUI/MenuController.cs
This will drop the item being build when switching menus. As a result of this change, it allows for ease of access to this clearing function, which might make the change in #630 easier.
Fixes #508
=> Drops the current build item when switching construction menus

Assets/Editor/SchedulerEditorTest.cs, Assets/Scripts/Scheduler/ScheduledEvent.cs, Assets/Scripts/Scheduler/Scheduler.cs, Assets/Scripts/UI/HeadlineController.cs
Fixes #1180 
Adds a `bool ScheduledEvent.IsSaveable` flag which is checked by `Scheduler` before serializing the event.
Also adds documentation comments per #1126. :grinning:
=> Allow disabling saves of ScheduledEvent. Fixes #1180.

Assets/Scripts/Models/World.cs
Fixes #1044
LoadSkybox was previously searching for available skyboxes as files, which don't exist in that form on a build. Changed to make use of LoadAll
=> Fix skybox loading in build - Fixes #1044

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/ISelectable.cs, Assets/Scripts/Models/Inventory.cs, Assets/Scripts/Models/Job.cs, Assets/Scripts/Models/Tile.cs, Assets/Scripts/UI/SelectionInfoTextField.cs
Improve the ISelectable to allow multiple string content controller by the class implementing the interface.
Added power info to power related furniture to display the current consumption, production and accumulated power.
(also change the hitpoint, stats & needs to be part of the additional info)
=> Better Selection Info + Power grid status display on furnitures

Assets/Resources/Shaders/Transparent-Diffuse.mat, Assets/Resources/Shaders/Transparent-Diffuse.mat.meta, Assets/Resources/Shaders/UI-Unlit-Transparent.mat, Assets/Resources/Shaders/UI-Unlit-Transparent.mat.meta, Assets/Scripts/UI/Overlay/OverlayMap.cs
Fixes #1218
The old method `Shader.Find()` works in the editor or if there is a reference to that shader in another file. By attaching the shader to a material and then using ```Resources.Load<Material>()``` allows the overlay to work again.
=> Fixes the issue of the overlay not working on build

Assets/Scripts/Models/Functions/LuaFunctions.cs, Assets/Scripts/Scheduler/Scheduler.cs
Previously there was no way for Lua scripts to access the Scheduler
directly. They could create or modify ScheduledEvent objects but not
actually (de)schedule them! This was a simple oversight on my part. The
intent for Lua access was there from the beginning.
Fixing this was simply a matter of adding a [MoonSharpUserData]
declaration and registering the globals. Now any Lua function run through
LuaFunctions.Call() or CallWithInstance() automatically gets the Scheduler
class and (most importantly) Scheduler.Current in its globals.
On commit all tests and Stylecop were passing.
=> [small] Makes the Scheduler class visible to Lua scripts

Assets/Scripts/Controllers/CameraController.cs
This allow to change the main camera initial zoom and fix a bug with empty value on start.
I have set the initial value higher than actually.
=> [small] Add a default zoom value on camera..

Assets/Scripts/UI/DialogBox/JobList/DialogBoxJobList.cs, Assets/Scripts/UI/InGameUI/MenuController.cs
- the work dialog did not check `isModal` before opening
- the work dialog did not set `isModal` when opening.
both caused other dialogs to be open at the same time as work. This PR addresses both issues.
=> Fix work dialog overlapping other dialogs

Assets/Scripts/UI/Overlay/OverlayMap.cs
By duplicating the material the file should not be changed at runtime, hopefully preventing changes from being included to the baseline that shouldn't be.
=> Prevent material change at runtime

Assets/Resources/UI/MenuLeft/ConstructionMenu.prefab
A small change in the construction menu scrollbar settings.
The MovementType going from Elastic to Clamped. This stop the bar for trying to go out of range.
=> [Small] Build Menu. Scrollbar settings.

Assets/Scripts/UI/Overlay/OverlayMap.cs, Assets/StreamingAssets/Overlay/overlay_functions.lua, Assets/_SCENE_.unity
Few changes on the overlayUI : 
- Fix a bug with oxygen map (LUA). Only 1 color is displayed if there is some O² in the room. Color change with O² still need to be added.
- Hide the overlayUI Tooltip if no overlay is displayed.
There is a small change in the scene on the dropdown menu : position and avoide streetching it.
=> Hide OverlayUI Tooltip

Assets/Scripts/UI/InGameUI/MenuLeft.cs, Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
when furniture is open, the dev menu is hidden so they don't overlap.
**Bug**: for some reason, when not in dev mode, the dev menu reappears after placing furniture.  `Settings.GetSetting("DialogBoxSettings_developerModeToggle", false)` is returning true after turning off dev mode and saving. likely a seperate bug from this PR
Edit: the bug occours on master as well. opened issue #1275 for it.
=> Hide Dev menu when opening furniture menu

Assets/Scripts/Models/Character.cs, Assets/Scripts/Models/EventAction.cs, Assets/Scripts/Models/Functions/FunctionsManager.cs, Assets/Scripts/Models/Need.cs, Assets/StreamingAssets/Data/Need.xml, Assets/StreamingAssets/LUA/Need.lua
* Changes Needs to no longer have hardcoded decay specific to Oxygen.
* Needs fires EventActions for updates (for specific decay/regular gain implementation for a need), and for various severity levels of the need. If no OnUpdate EventAction is defined it will use a default Update to decay needs. OnEmptyNeed will also have default, but it currently does nothing as there is not yet good supporting framework, particularly for Oxygen, to have negative actions on an empty need.
* Needs still run from 0 (good) to 100 (bad - empty), as code outside of Need relies on that ordering, and I wanted to minimize files touched outside of Need, until the game could better support Need directly handling what a character does when a need needs fulfilled.
This includes changes to EventActions:
EventActions …
=> Redo needs

Assets/Scripts/Models/World.cs
Fixes #1305.
The serialization was creating a new World using the empty constructor and in doing so attaching the events, which triggered but everything in the world was empty. I moved the attachment to SetupWorld.
=> Attach the events on World Setup

Assets/StreamingAssets/LUA/Furniture.lua
Mining drone and many other furniture's don't work because I didn't properly update them to use job.buildable in lua. This fixes that, along with changing all incidences of `j` to `job`.
=> [HotFix] Fix lua to use job.buildable

Assets/Scripts/Models/ContextMenu/ContextMenuAction.cs, Assets/Scripts/Models/Furniture.cs
There is an unusual bug that this fixes that is caused by the "Action" being placed in the same piece of memory for each object yielded. The bottom line is, only the second action was possible. I'm not sure why this is the case, and I tried many means to force the two to occupy different pieces of memory, but I failed. This workaround, however, works well, and it can make it easier to debug such issues in the future.
=> Fix context actions from lua

Assets/Scripts/Models/Furniture.cs, Assets/Scripts/Models/State.meta, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/LUA/Furniture.lua
I added a trigger for furniture, when they lose power, as per issue #1312.
I used the new animation system for:
Oxygen generator - now animates, and when power is off it returns to idle state.
Oxygen compressor - This doesn't return to an idle state when turned off, but it leaks half of it's compressed gas. 
I'm not sure if that's the effect it should have, but it's a nice testcase for this event trigger, as we don't always want furniture to return to "idle" when unpowered.
Feedback is appreciated!
=> Furniture loss of power event

Scripts/Contributor_Name_List.py
The previous script didn't paginate, this one does. It also uses a slightly faster API.
The capitalization script was changed to permit people to have upper case characters other than the first character in their user names.
=> Contributor script over 100

Assets/StreamingAssets/Data/Furniture.xml
I defined the value based animation for the vent in the wrong order, leading to it using the closed sprite for the opened state and vice versa. It however wasn't noticeable due to also having the sprites defined incorrectly in XML.
The Sprite XML should be fixed in #1379, this just fixes the animation state definition.
=> [Small, Fix] Fix Vent Sprite Animation order

Assets/Scripts/Controllers/Sprites/FurnitureSpriteController.cs
Fixes #1389 
The sorting layer was being assigned before the position of the game object was set. It was defaulting to 0 for all loaded furniture sprites.
=> [Tiny, Fix] Sorting order of furniture now being applied on load

Assets/Resources/Prefab/ContextMenuItem.prefab
offsets the context menu text by 5 pixels.
=> [Small] Offset context menu text

Assets/Scripts/UI/ContextMenu/ContextMenu.cs
While working on deconstructing utilities, I found the context menus for utilities weren't wired up. I've addressed that issue with this PR.
=> Adding Utilities to possible Context Menu Actions

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/Models/Buildable/Furniture.cs
#1352 set up the ability to have build locations that aren't on the main part of the furniture. It seems that this will cause anything that has a build spot on the furniture, or no build spot, to not work. I've commented out this line until we can properly resolve that issue.
=> [Hotfix] Disables the prototype reserving the space for now

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Functions/FunctionsManager.cs
Reverts #1403 and replaces with a fix to the problem patched by 1403 by unreserving the workspot prior to trying to place the furniture.
=> Reenable pending furniture workspot reservation, unreserve before furniture placement

Assets/Scripts/Models/Area/RoomManager.cs
Rooms were only being split if they were the outside room. This removes the check for outside room which is no longer needed.
=> [Fixes #1405] Fix Room Splitting

Assets/Scripts/Models/Functions/LuaFunctions.cs, Assets/StreamingAssets/LUA/Furniture.lua
PR #1072 made the change in Room and all C# code, but neglected to check
for Lua references. These wound up giving error (c.f. #1406).
This just changes to references to the new name.
Also added a null check in LuaFunctions::CallWithInstance because the
return value of the Lua call can be null.
Fixes #1406.
=> Fix Lua references to room.GetSize to use room.TileCount

Assets/Scripts/Models/Buildable/FurnitureWorkshop.cs
Power cell should now get all the materials needed:
removed old code (evidently not active until recently)
This should fix #1311 and hopefully #975 is now testable again..
=> Fix for workshop jobs getting cancelled

Scripts/Contributor_Name_List.py
Uses a bit of trickery to make it happen, namely relying on a different API, as the localization repository is effectively housed in a branch.
Fixes #1401
=> Add in names from the Localization database

Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Events/EventAction.cs, Assets/StreamingAssets/Data/Furniture.xml
Fixes #1383 
Duplicate the EventAction in furniture to add FrameAction
EventAction behavior unchanged
FrameAction will be call every frame, so animation can be smooth
Fix the "door slam open effect"
=> Add a fast update (every frame)  to furniture to allow smooth animation

Assets/Scripts/Controllers/InputOutput/CameraController.cs, Assets/Scripts/Controllers/WorldController.cs, Assets/Scripts/Models/Area/World.cs
This keeps track of visible and invisible furniture, so we can manage update frequency of visible furniture. See #1383.
I'll let this one wait for #1400 to be finished, as they are closely related.
=> World update frequency for visible/invisible furniture

Assets/StreamingAssets/LUA/Furniture.lua
when cloning pod was placed it was throwing error because of properties moving to different classes and some methods being properties now
=> [Fix] Cloning pod was broken after refactoring

Assets/Scripts/Models/Area/RoomManager.cs
Currently, in master, any new walls placed have room 0, the outside room, rather than a null room, this causes issues when removing that wall as adjacent rooms won't be joined. Removing the explicit assignment to outside room of any tiles from a removed room doesn't seem to cause any issues, tiles in a room opened to space are still properly assigned to the outside, and new walls will once again have null room.
=> [Small, Fix] Don't assign RoomEnclosing furniture to outside Room

Scripts/test.sh
[Schellcheck](http://www.shellcheck.net/) is a linter and static analysis tool for shell scripts. I have done a pass over Scripts/*.sh and fixed all of the issues it highlighted.
=> [small] Shellchecking Travis scripts

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Models/Buildable/Utility.cs, Assets/StreamingAssets/Data/Utility.xml
Utilities did not deconstruct previously, both because BMC didn't call deconstruct on utilities, and the utilities deconstruct method didn't handle things properly.
Deconstruction will now first look for a furniture to deconstruct, and then if there is a pending build job, will cancel it (as before) and then deconstruct the last utility built.
This may not be that absolutely best optimal desired behavior (I would like to be able to have things figure out to delete power cables if you've drug deconstruct over power cables, but that would require much more complicated logic, and possibly drastic changes to how the buildModeController performs deconstruction.) but it is functional whereas previously it was not and would completely destroy the utilities hashSet making it impossible for any …
=> [Fix] Properly deconstruct utilities

Assets/Scripts/Models/Area/Room.cs, Assets/Scripts/Models/Area/RoomManager.cs
This fixes a problem with old rooms not being deleted when rooms are joined (Rooms would stay in RoomManager).
It also fixes a problem when splitting rooms where the gas pressure would be directly copied to the new room, effectively causing a loss of total gasses in the rooms (Gas Pressure now goes up a slight amount when rooms are split, due to more of the space the gas would otherwise be in being occupied by a wall, this matches the behavior where the gas pressure drops when a wall is removed.)
Also renamed CopyGasPreasure to SplitGas, to more accurately reflect what is happening.
=> [Small] Better Room Splitting and Joining

Assets/Scripts/Models/Buildable/Furniture.cs
Furniture is for some reason cloned when trying to place it in world (MouseController.cs). Cloning of furniture already plugged in the furniture into network - this spawned lots of shadow users => resulted in power shortage.
Overall the furniture cloning is kind of popular in code and needs to be reduced.
=> [Fix] PowerConnection plugged in when cloning

Assets/Scripts/Models/Area/Room.cs
Unassign tiles should return when tile isn't in room, not when in room.
Fixes #1480
=> [Small, Fix] Fix oldRoom not empty error

Assets/Scripts/UI/InGameUI/GameMenu/GameMenuController.cs
Prevents an exception with the following stacktrace by adding a try block:
```
MissingReferenceException: The object of type 'GameObject' has been
destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy
the object.
GameMenuController+<CreateButton>c__AnonStorey41.<>m__88 () (at
Assets/Scripts/UI/InGameUI/GameMenu/GameMenuController.cs:80)
ProjectPorcupine.Localization.LocalizationTable.LoadingLanguagesFinished
() (at Assets/Scripts/Localization/LocalizationTable.cs:83)
ProjectPorcupine.Localization.LocalizationLoader.UpdateLocalizationTable
() (at Assets/Scripts/Localization/LocalizationLoader.cs:44)
ProjectPorcupine.Localization.LocalizationLoader.<Awake>m__2F () (at
Assets/Scripts/Localization/LocalizationLoader.cs:85) …
```
=> Fix MissingReferenceException thrown when saving settings

Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
ConstructionMenu.Update() was checking if language had been changed and was manually changing button names but in the wrong way (was assuming there were no buttons other than Furniture build buttons), removing the Update function allows events to properly take care of updating language.
=> [Small, Fix] Don't overwrite Construction menu names in Update

Assets/Scripts/State/JobState.cs, Assets/Scripts/State/MoveState.cs
Fixes an issue where character waits until the end of a tile move to change facing, which lead to "moonwalking" at the start of pathing and is especially prominent during pathfinding that is only one-tile long.
An additional change makes the character face in the directly of the job tile for adjacent-position jobs.
In particular, this fixes some funny movement during floor construction.
=> Facing Fix - One-Tile Movement and Job Facing

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs
Simple and only partial fix for #1459, later whole saving operation should be threaded.
=> Saving World to HDD moved to a separate thread

Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/State/MoveState.cs
Neither characters nor pathfinding were properly taking into account Z, meaning they instantly moved up and down (and also considered up and down to basically 0 distance.
This just adds a quick calculation for tiles directly above and below, and includes Z into the calculations for distance both for PathAstar and MoveState
=> Better up/down movement

Assets/Scripts/UI/DialogBox/Options/DialogBoxOptions.cs, Assets/StreamingAssets/Localization/en_US.lang
user is now prompted to confirm quitting the game when hitting quit in the options menu.
=> [Small] Confirm Quit dialog

Assets/Scripts/Localization/LocalizationLoader.cs
I'm not sure why UpdateLocalizationTable needs called from both awake and start, but I tried removing it from awake, and things didn't work.... so... o.O I don't really know why it's still needed in awake... not even trying to touch the other one in the delegate because there's certainly some stuff going on that I don't fully understand... but at least this works as advertised :D
=> Update Localization table in Start

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs
Before that user would see "saving complete" pop-up, but in reality a separate thread was still writing data.
Also - I disabled dumping raw XML onto editor's console because it was really hanging the editor.
Sorry for not including this in #1496
=> Correctly wait for saving to be completed

Assets/Scripts/Models/Area/World.cs
Moved the tilegraph creation to the world constructor. This way the tilegraph is created when the world is initialized instead of on the first job request.
=> Initial job lag fix

Assets/Scripts/Models/Job/Job.cs, Assets/Scripts/State/JobState.cs
Fixes #1505
Repeating jobs weren't being returned to the queue or being cancelled, but characters silently dumped them when finished with one cycle. They now keep the job if it is a repeating job (added a public property to see if a job repeats), only abandoning it if something else comes up, this seems to most closely match pre-FSM behavior, and seems more desirable to have a single character keep working a job as long as nothing else interrupts them, rather than repeatedly returning it to the queue and having new characters take turns doing it.
=> [Fix, Small] Characters continue working repeating jobs

Assets/Scripts/UI/DialogBox/FileSaveLoad/DialogBoxSaveGame.cs
- remove commented out code from when saves were done in a playerpref 
- fixed stylecop error for no space between `//` and comment text
Ill be self merging this since it doesn't touch any real code and I didn't catch the stylecop error when I merged a previous PR
=> Remove commented out code and fix stylecop violation

Assets/Scripts/Localization/LocalizationTable.cs, Assets/Scripts/UI/LanguageDropdownUpdater.cs, Assets/StreamingAssets/Localization/en_US.lang
The options menu now localizes the languages you can select. It does this at the moment only for US English, but the people who work on localization can add this to other languages too. This is to finally close #358 and this is also a milestone for Version 0.2.
=> [Fix, Small] Options Menu now Localizes Languages

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
These templates are automatically filled in the editor textarea when
someone creates an Issue or Pull request on Github.
The text can be changed or deleted at will by the user, it is there merely
to serve as a prompt to include the pertinent information and format it in
a useful way.
Here is an example of how this PR might look if using the template:
----
Issues and pull request messages have been of very uneven quality. I am as guilty as anyone in terms of including inadequate or poorly presented information in pull requests. But over the history of the project so far, people have submitted things ranging from impossible to read stream of consciousness style messages, to messages with no informative content at all.
Luckily Github makes it possible to create …
=> Create Github Issue and Pull Request templates

Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Pathfinding/Path_AStar.cs, Assets/Scripts/Pathfinding/Path_TileGraph.cs, Assets/Scripts/Pathfinding/Pathfinder.cs, Assets/Scripts/UI/VisualPath.cs
Currently, characters will travel up through newly place floor tiles, and will work on a tile from below, even if there is a floor tile in the way.
This regenerates the tilegraph around the tile below a newly placed tile, making the tileGraph aware that access to the tile from below is blocked by the floor tile. A separate check is added when getting acceptable tiles to work adjacent from so that a floor tile in the tile that needs to be worked will block adjacency from below.
Additionally minor changes were made to GetNeighbors (vertical adjacency is optional, and off by default, and the vertical adjacency is farmed to a separate method, to allow access to only vertical neighbors for situations when they need to be handled specially. Also convenience methods were added to access the Up …
=> [Fix] Don't phase through floors traveling up, and don't work through floor tiles

Assets/Scripts/Models/Settings.cs, Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs
As described in #1525 currently due to using the scheduler, settings don't save when paused. 
I have opted to fix this by, rather than saving settings or scheduling a save when a setting is changed, removing SaveSettings from SetSetting, and explicitly saving the settings after all settings have been set.
Fixes #1525
=> [Fix] Set Settings then Save Settings explicitly

Assets/Scripts/Models/Character/Character.cs
I adjust characters speed with this formula.
speed = baseSpeed +/-30% of baseSpeed depending on Dexterity.
The baseSpeed is 5 tile per sec. So it can go from 3.5 to 6.5.
The original formula is Dexterity / 2 so there is a range of 0.5 to 10. It feel a little too extreme.
=> Adjust Charaters speed.

Assets/Scripts/Models/Functions/Parameter.cs
Parameter Autocreation is an intended feature, and shouldn't generate a warning.
=> [Small, Fix] Remove Warning from Parameter Autocreation

Assets/Scripts/Models/Inventory/InventoryManager.cs
Fixes bug where loading character inventory gave Dictionary - keys doesn't exist exception.
To reproduce: save game while character is holding some inventory, load it.
As jobs are not persisted yet, character will hold the inventory, but he 'forgets' what he was doing...
=> [Fix] Fixes crash when loading save with character carrying inventory

Assets/Scripts/Models/Buildable/Components/Workshop.cs
When deconstructing Metal furnace without previously assigning any 'recipe' to it there is a null reference exception - and then spawning of stuff from deconstruct job..
#1567
=> [Fix] Fixes deconstructing of workshop (metal furnace)

Assets/Scripts/Controllers/Sprites/FurnitureSpriteController.cs, Assets/Scripts/Models/Buildable/Furniture.cs
Fixes issue when power icon was not appearing after placement of new furniture (initialize) and there was lack of power. Machines were not operational though (correct behavior).. so only icons were not synced.
=> [Fix] Fixes power icons update on furniture placement

Assets/Scripts/Models/Buildable/Components/Workshop.cs
Fixes 'Argument cannot be null' when trying to get context menu on workshops with one production chain (power generator, power cell press)
=> [Fix] Fixes context menu for workshops with 1 prod. chain

.github/ISSUE_TEMPLATE.md
Adds the following to the top of the issue template:
> _this template is for reporting bugs or issues in the current game. You don't need to use it if you are suggesting a feature or starting a discussion_
Some feature requests and discussions are using the template despite it being intended for bugs. Hopefully this change will clear that up.
=> Add clarification in issue template

Assets/Scripts/Pathfinding/Path_TileGraph.cs
When building a tile on the lowest layer, an error will occur due to a null tile (the down tile from the tile being built) being passed to RegenerateGraphAtTile. This simply returns from RegenerateGraphAtTile if passed a null tile.
=> [Tiny, Fix] Fix error on building tiles on lowest layer

README.md
Simply put just replaces the Readme.md image with a more recent one, the old one had options in the wrong place and was using the old fps counter (and all the machines had the no power indicator).
New Image:
=> [Super Small] Update Readme.md with a more recent image

Assets/StreamingAssets/LUA/Furniture.lua
fixes an outdated function name being used in furniture.lua.
`UChannelLogWarning -> ULogWarningChannel`
=> [Small] Fix incorrect logging fuction name in lua

Assets/Scripts/Models/Buildable/Furniture.cs
When creating a new world, asteroids that spawn on top of the base raise an exception. This PR changes the call to a warning since its not a problem and fairly common.
=> [Small] Change furniture placement error to warning

Assets/Scripts/Models/Functions/LuaFunctions.cs
Currently lua runtime errors (such as trying to access an inaccessible part of userdata) can be a little difficult to debug as they don't specifically say what script is calling them, this PR stores the script name in a private field and includes that in the error message generated when an error is encountered running a script.
Also lua called with CallWithInstance generates an error message with the script name.
=> [Small, Fix] Slightly better Lua Error messages

Assets/Scripts/UI/DialogBox/Settings/DialogBoxSettings.cs
Currently saving settings fails on main menu due to trying to access WorldController.Instance, which is null at the time. This checks for null and skips trying to update the autosaveManager (which doesn't exist at the time and therefore doesn't need directly updated, with the new autosave settings.
Fixes #1599
=> [Fix] Fix Error on saving settings from main menu

Assets/Scripts/UI/DialogBox/Trade/DialogBoxTrade.cs
A small fix. 
The prefab have been moved but the path is still on previous location.
=> [Small][Fix] Wrong path to TradeItem Prefab

Assets/Settings.StyleCop, Assets/Settings.StyleCop.meta, Settings.StyleCop
Currently our stylecop settings are merged with system defaults, however, apparently there are differences between the defaults of Visual Stylecop and Monodevelop Stylecop, one recent example is the differences in the exception list for the Hungarian rule (Monodevelop Stylecop has x, y, and z as exceptions, whereas Visual Stylecop doesn't).
This sets our settings as standalone (not merged with defaults), so differences between the defaults won't cause issues. One notable exception is Monodevelop Stylecop won't raise a violation when there is a space after the license header (as shown in following), whereas VIsual Stylecop will. 
```
#region License
// ====================================================
// Project Porcupine Copyright(C) 2016 Team Porcupine
// This program comes with …
```
=> Standalone Stylecop settings

README.md
The download link goes to a unity beta download, which is for 5.5.0. Unity 5.4 is now stable.
=> [Small] Update Unity 5.4 download link to stable

Assets/Scripts/UI/MouseOver.cs, Assets/Scripts/UI/MouseOverRoomDetails.cs
Removed commented out code inside MouseOverRoomDetail and fixed a summary in MouseOver.
No code was altered.
=> [Small] Remove commented out code in MouseOver classes

Assets/Scripts/Models/Buildable/FurnitureManager.cs, Assets/StreamingAssets/LUA/Quest.lua
This PR fixes quests. They can now be completed and reward inventory will be placed.
Fixes #1559 
Closes #1559 
- Exposes the FurnitureManager to lua in order to query if the furniture required to complete the quest are built.
- Fixes function call to get the number of furniture of a type.
- Fixes function call to get the tile closes to center tile to place the rewards.
=> Fix quest furniture counting and reward inventory placing (#1559)

CONTRIBUTING.md
A lot of people are creating their first PR with stylecop errors and other slight problems that is due to not reading the Contributing Guidelines, this just adds the link (as a relative so it should work with forks and locals).
=> Added reference to Contributing Guidelines in the Contributing.md

Assets/StreamingAssets/UI/DialogBoxes/TestDB.xml
Standalone build errors with `encoding="Windows-1252"`, causing only the construct button to be shown on standalone. Changing to ` encoding="utf-8"` fixes this.
Closes #1591
=> Change TestDB xml encoding to utf-8

Assets/Scripts/Controllers/InputOutput/MouseController.cs
Dev mode setting name was changed but Mouse Controller used the old setting name, leading to an inability to queue utility jobs.
=> [Fix] Change dev mode setting name used by mouse controller

Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Area/WorldGenerator.cs
World gen was crashing due to trying it trying remove the floor under a wall, because IsStartArea had an off by one error in the Y direction. This adjusts the Y bounds. 
Additionally the World Seed in now logged to the console to aid in future debugging of anything that is inconsistent based on world generation.
=> Fix crash on world gen

Assets/Scripts/Controllers/InputOutput/MouseController.cs
Currently there is a bug where you can attempt to build tiles off of the map, this causes an error due to the null tile (only BuildMode.Furniture and BuildMode.Utility check for null). This fixes that bug by moving the null check outside of the code for BuildMode.Furniture and BuildMode.Utility, instead skipping the entire tile if it is null, regardless of the BuildMode.
=> [Fix] Prevent Building Tiles off the map

Assets/Scripts/UI/InGameUI/DevConsole/DevConsole.cs
Removes the UnInit Method from dev console, since it serves no purpose.
=> Remove unnecessary uninit code from dev console

Assets/Scripts/Models/Keyboard/KeyboardManager.cs, Assets/Scripts/UI/CursorInfoDisplay.cs, Assets/Scripts/UI/MouseCursor.cs
There is no real indication of what the z index of the tile under the mouse is. This makes it hard to test other PRs and use dev console commands.
Adds the Z level of the tile that the mouses is over. (toggled by Ctrl + M as before)
I also re implemented the toggling of this behavior to use the Keyboard Manager as opposed to unity's default input system.
=> Add z level to mouse cursor text

Assets/Scripts/Models/Area/WorldGenerator.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Buildable/Utility.cs
Closes #1660
This removes MinEdgeDistance, which I don't believe is needed any more.
Verbatim copy of text in #1660 as to why I believe MinEdgeDistance is no longer needed:
Currently we have MinEdgeDistance of 5, which prevents you from building within 5 of the edge of the map, this was originally instituted to solve a bug related to building right along the border. However, preliminary tests suggest that even with MinEdgeDistance set to 0, no errors are caused by building near the edge of the map (there is an error if you try to build tiles off of the map, but that isn't related to setting MinEdgeDistance to 0 and is present in master).
Update: Since this has not seemed to create any unforeseen bugs, I've now fully removed MinEdgeDistance, and consider this viable for merging.
=> Remove MinEdgeDistance

Assets/Scripts/Controllers/InputOutput/SoundController.cs, Assets/Scripts/Controllers/Sprites/TileSpriteController.cs, Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Models/InputOutput/AudioManager.cs
Currently on master, when a save file is loaded all tiles loaded from the save file will have ForceTileUpdate set to true, which means when they are walked on, they will end up triggering their Tile Built sound, because walking on a tile updates the walk count, which triggers the TileChanged event.  I'm uncertain as to why this doesn't seem to happen at other times when tile data is forced to change (perhaps it isn't regularly forced on walking on it, I haven't investigated deeply).
However, just no setting ForceTileUpdate to false causes any worn tiles to not display properly on file load.
To solve this I have created a separate TileTypeChanged event, which is subscribed to by the SoundController rather than TileChanged, so that sounds will only be made when a tile's type is changed.
=> [Fix] Separate TileTypeChanged Event

Assets/Editor/DebuggerChannelControl.cs
Sometimes the debugger channel control window can have wierd bugs after changing to and from PR branches: 
This can be fixed by deleting ChannelSettings.asset and then reloading the window, but requires a manual restart of unity.
adds a nifty option in the right click menu of the DebuggerChannelWindow tab that allows you to reload the window without quiting unity.
=> Reload debug channel controller via context menu

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/Models/Character/CharacterManager.cs, Assets/Scripts/Models/Inventory/InventoryManager.cs
Just a trio of quick bugfixes.
Fixes the error on doing a deconstruction where no object to deconstruct exists.
Fixes inventoryManager incorrectly saving inventory with no tile (and therefore somewhere other than a tile, and appropriately handled elsewhere).
Fixes character not loading inventory saved under it.
=> Bugfixes (Area Deconstruction, Character Inventory Saving/Loading

Assets/Scripts/Models/Inventory/Inventory.cs, Assets/Scripts/Models/Inventory/InventoryManager.cs, Assets/Scripts/State/HaulState.cs
Presently characters will all try to go after the same inventory, this PR simply stores a claim in the form of a DateTime object, and will prevent a character from finding an inventory with a claim more recent than 5 seconds, and resets the claim time on pickup so that if they don't pick up the full stack it is now available for another character. DateTime is used rather than a boolean or the character with a claim so that it autoexpires, without needing any event to be subscribed to or an update sent to inventory. Optimally we will, in the future, implement a form of in game time that can be used to track claims (along with many other uses of such a system), however, as is, using DateTime, a claim will expire if the game is paused right after a character claims an inventory, allowing …
=> [Small] Claim inventory

Assets/Scripts/Models/Buildable/UtilityManager.cs
Utilities didn't correctly build the network when loading from a save, they were trying to build them as soon as they were placed (rather than after all were placed) which can prevent all connected wires from being on the same network, if there's a fork in the wiring and depending on the wiring (if the network at some point has two separate parts that will later be joined, they won't join properly, since each fork will have already decided on its grid.
Fixes #1677
=> Fix Utility Network Build on load

Assets/Scripts/Models/Area/Room.cs, Assets/Scripts/UI/InGameUI/DevConsole/DevConsole.cs, Assets/Scripts/UI/InGameUI/DevConsole/DevConsoleCoreCommands.cs
Adds dev console commands to control atmosphere, either of individual rooms (by roomID) or all rooms, also by individual gas or standard human breathable atmosphere mix, and finally commands to empty the atmosphere of rooms. Includes SetGas command in Room.cs (used in the DevConsole commands), to directly set the gas mixture in a room, rather than changing the already present gasses.
=> Atmosphere control dev commands

Assets/StreamingAssets/Data/Furniture.xml
Walls still had DeconstructJob rather than OrderAction, just simply swapped it over to OrderAction.
=> Fix Wall Deconstruction

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs, Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs
Just applying the same fix to the OrdersMenu that is used by ConstructionMenu to close the InventorySpawning Menu when it's opened.
=> Fix inventory spawn overlaying orders

Assets/Scripts/Models/Area/RoomManager.cs
Another PR switching to HashSets where feasible. For RoomManager, this is in some portions of of the FloodFill code, and Gas Equalization. This reduces some of the fps losses on placing an enclosing furniture, and small gains during regular equalization (which happens regularly, when you have doors or vents)
=> [Small] Use HashSets for RoomManager

Assets/Scripts/Models/Buildable/FurnitureManager.cs
Any time the camera is moved, furniture is shuffled from an invisible list to a visible list and back, so that updates are ran slower on furniture that is out of frame. However, this can take 100+-20 ms to complete, which leads to a bit of stuttery movement. However, simply changing it to use HashSets drops it to somewhere between 8 and 20 (not exactly sure, as it doesn't create a visible spike as it does in master, so it's not as easy to pick out).
In more extreme cases (such as a world with more/larger asteroids, and thereby a lot more furniture), this can drop a 400-800 ms process to around 200, which, while still high, still leaves a playable framerate. 
This is partially to alleviate the loss of frames when scrolling presently on master, but also in preparation for larger more …
=> [Tiny] in/visible furniture to HashSet

Assets/Scripts/State/IdleState.cs
Another small optimization, with an appreciable effect.
Currently crew in an idle state select one adjacent tile, and pathfind to it. This is done with a fair amount of regularity, and even though it is pathfinding to an adjacent tile, it can take a reasonable amount of time and this causes the game to have fairly regular fps drops, with the occasional very large spike (400ms spent in pathfinder, though I don't know why it does this only occasionally).
Since crew are only walking to an adjacent tile, and they already check if it is walkable, the pathfinding can be skipped, instead creating a list containing the current tile and the end tile, and feeding that directly to moveState. This makes the regular usage of idle state negligible (in the range of .05 ms), and eliminates the spikes (or …
=> [Tiny] Don't Pathfind to adjacent tiles in Idle

Assets/Scripts/Models/Character/CharacterNameManager.cs
I was just looking for lists to change to hashsets, and came across the name manager which utilised two queues to maintain a cycle of names.  This just replaces that with a single array and an int (which acts like a pointer), and it just cycles that pointer till the end then cycles it over again, overall this is faster and requires less space and is faster, it doesn't have to create a new array (when adding new names) it just sets the array to a concencated one so no weird heap stuff there either.  I know this is probably quite subjective and probably quite a few people think that it's not really necessary, and kind of random but I just came across it randomly and thought hey I'll propose a different structure that's a little more typed :D (and it actually requires less GC since it …
=> Changed the double queues to a single array in CharacterNameManager

Assets/Scripts/Models/Buildable/Tile.cs, Assets/Scripts/Pathfinding/Pathfinder.cs, Assets/Scripts/Pathfinding/RoomPath_AStar.cs
Currently, in master, any pathfinding that uses room pathfinding will fail if starting from a null room (such as a door. This first has it use GetNearestRoom, so that it will look for an adjacent room, failing that it will now also try to get the nearest room via pathfinding, and for the worst case scenario (room filled with doors, and not connected to any other areas, so there are no room objects accessible, it should just try to dijkstra pathfind to what it is looking for. I feel this worse case is going to be exceedingly rare, and further if it does happen will be unlikely to be a large room, so dijkstra shouldn't be a big performance hit, and if it is, this is a player trying to push the edge of what is reasonable and likely is doing it for no reason other than to break the system, …
=> Failsafes for pathfinding from null room

README.md
Closes #1707.
Just since due to the problems (covered in detail in #1707 by @koosemose), it was established that we won't be migrating to 5.5 (or any future release) till its more reliable (or till it has features we desperately need).
=> Just to remove the notice about migration.

Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs, Assets/Scripts/UI/InGameUI/MenuLeft/OrderMenu.cs
Fixes #1700
Due to changes in ConstructionMenu the Filter was no longer working. This simply adds the Listener through code. It also adds the listener to the similar Filter in the order menu, which while not strictly needed at this time, due to the small size of the order menu, it does have the Filter field present and may be needed in the future.
=> [Fix] Reconnect FilterField to FilterFunction

Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs
Just me being a little stupid and forgetting to do a check so it'll only escape the menu if its open.  This way you don't have weird inconsistencies with it trying to close and it's already closed.
=> Escape always exists the settings menu

Assets/Scripts/Models/Area/World.cs, Assets/Scripts/Models/Buildable/Utility.cs, Assets/Scripts/Models/Buildable/UtilityManager.cs
When I created Utility.cs off the basis of Furniture.cs, I left in the update functions, because at the time I was uncertain exactly how various aspects of the actual networks would be implemented, and wanted to leave them in in case they were applicable, however, now that I've started integrating the appropriate systems, I can see they're not going to be used. This removes the update functions, and the various calls to them that did nothing but waste a bit of time.
=> Remove Utility's Update functions

.travis.yml
The current config.yml instructs travis to install rvm, which is not needed for PP. This PR removes it.
=> Remove rvm from travis configuration

Assets/Scripts/Models/Events/EventAction.cs, Assets/Scripts/Models/Events/GameEvent.cs, Assets/Scripts/Models/Functions/Functions.cs
While profiling in my experiments to improve TimeManager and our general usage of UpdateFunctions, I narrowed in on a fair amount of GC allocation coming from EventActions (and in turn from Functions.cs). 
So I've went through the class (Functions.cs) and tried to minimize object creation and Foreach loops. Most notably, CallWithInstance is now passed a List, rather than an array as in both instances where it is called the object stored by the caller is a list, requiring it to be converted to an array, and creating another object to be garbage collected. Additionally FunctionSets is changed to a list, since, while order doesn't matter, it is small and isn't frequently added to/removed from, which means difference in function between the two is negligible, but changing it to a List allows …
=> Less Object Creation in Functions.cs

Assets/Scripts/Models/Area/Temperature.cs, Assets/Scripts/Models/Area/World.cs, Assets/Scripts/UI/MouseOverRoomDetails.cs, Assets/Scripts/UI/Overlay/OverlayMap.cs, Assets/StreamingAssets/LUA/Furniture.lua
Temperature.cs has a few issues, this fixes some of them.
Temperature progression does not take delta time into account, so as best I can tell it functions as though 1 second has passed every update cycle (presently 1/5 second), this includes delta time in the calculations in the place that the comments imply it should be.
The two objects that update temperature both call the same function eventually, and furthermore I don't see a reason that things would do any different and heat things with some other calculations, this moves that function into C#, preventing a large number of heat sources from bogging the game down quite so bad.
The Temperature update event action for heat sources was being registered twice, once automatically via the xml, and again manually in the install event …
=> Optimize temperature

Assets/Scripts/Models/Buildable/Utility.cs, Assets/Scripts/Models/Time/TimeManager.cs
Previously I removed updates frame Utilities on the premise that they did nothing. However, I overlooked on thing, and that is resetting the boolean that says rather or not they had updated their network that frame, to prevent them from getting stuck in an endless loop, crawling up and down the network of wires trying to build the network.
I still stand by removing the update, because it was way too much just for one little thing that is only used for one maintenance level thing and only when utilities are built. 
To reimplement the reset, I implemented a method in TimeManager, RunNextFrame, which simply takes an action with no parameters, and runs it on the next frame before anything other updates are processed.
=> [Fix] building utility network  -- reset updated this frame

README.md
Feathub is barely used and we have little control and can't police it (such as removing the "memes" suggestion), or remove already implemented features.
=> Remove FeatHub link from Readme

Assets/Scripts/Controllers/InputOutput/SoundController.cs
Previously there was no way to control sound without directly accessing the AudioSystem, and dealing with the C-Style api of Fmod, this adds SetVolume and GetVolume in SoundController, along with an AudioChannel enum to help provide smoother access without having to use strings (though accessing with strings is still available.
These hookups are being put in place to be accessed by #1737
=> Volume Control in SoundController

Assets/Scripts/Models/InputOutput/AudioManager.cs, ProjectSettings/ProjectSettings.asset
For me this seemed to fix the memory leak.  The problem was it wasn't creating the sound system again in the editor (requiring you to quit the unity editor and reopen), this _seems_ to have fixed it.  If it hasn't fixed it for you then just post some basic computer info (version of system running/os.  I.e. MacOS Sierra Version x, or Windows 7 Version y so on)...
I didn't do much other than get the system to close (stopping all handles), then releasing the channels then finishing it with releasing the sound system.
=> [Fix] Fixed FMOD Memory leak in editor?

Assets/Scripts/Models/Area/World.cs
Simply saves the original world seed to the save file (both for later recovery of the seed, and in case it is needed to facilitate future multiple world generation of some sort), and the random state (meaning anything past world generation that depends on the seed won't be based off a random seed on world load, but instead on the original seed (and where it developed to after multiple Random calls).
Required some slightly awkward workarounds, as JSON.net is unable to automatically serialize Random.State, and none of it's fields are accessible, so it can't be manually serialized, so I use JSONUtility to convert it to/from a Json string feeds to/from Json.net to generate the appropriate object.
If a seed or random state isn't saved in the save file, it will leave everything as is, meaning …
=> Save/Load Seed and Random.State

Assets/Editor/DebuggerChannelControl.cs, ProjectSettings/ProjectSettings.asset
Without this work around, sometimes the ChannelSettingSO would be removed but the Editor was still refrencing it without creating a new one. 
This prevents this by checking that it exists before accessing it when marking settings as dirty. It recalls the Awake function if the ChannelSettingsSO doesn't exist, thus preventing errors when interacting with the Debugger Channel Control when this edge case occurs.
=> [Small] Fix Errors when reseting debug channel filter

Assets/Scripts/Models/Job/JobQueue.cs, Assets/Scripts/Pathfinding/Pathfinder.cs, Assets/Scripts/State/HaulState.cs
I made a mistake when implementing RoomPathfinding,  I missed an inventory.CanBePickedUp, so it was pathing to the stockpile, and being told it can't pick it up, and therefore requesting a new path, and being told about the same inventory so they get stuck in a loop of that, so all crew eventually end up stuck in stockpiles, hammering the pathfinding.
This properly adds a check that the inventory can be picked up before pathing to it.
=> [Fix] Properly return a path to an inventory that can actually be picked up

Assets/Scripts/Models/Inventory/Inventory.cs
GameTime was created secondarily to in my TimeManger updates, this simply changes the inventory claim system to use GameTime rather than real world time.
=> use GameTime in inventory Claims

Assets/Scripts/Models/Buildable/Components/PowerConnection.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/Models/Buildable/Utility.cs
Connects Power consuming/generating furniture to cables in any of its tiles (both when the furniture is placed, and when a utility is placed). 
Also adds a utility function to furniture to support, `Tile[] GetAllTiles()` so that a loop doesn't have to be recoded every time all tiles of a furniture are needed, and to simplify breaking out of looping once a utility is found to connect to.
As the Fluid Network is still Universal at this time, the same logic isn't applied to the Fluid Connection, but should be easy to implement when Fluids through pipes is implemented.
=> Try to connect to power utility in all tiles of furniture

Assets/Scripts/Controllers/MainMenuController.cs, Assets/Scripts/UI/InGameUI/MenuTop/CurrencyDisplay.cs
Atemporary fix for an issue from #1722 where the currency UI would be active in main menu and cause null refrence errors. This is not a permanent fix, and should be noted/fixed when the UI is fixed by @BraedonWooding.
=> Disable currency UI in main menu

Assets/Scripts/Models/Functions/LuaFunctions.cs, Assets/Scripts/Models/Settings/Settings.cs
Previously Settings was inaccessible to Lua, and after being made accessible the standard GetSetting could not be used (some combination of generic function and an `out` parameter did not play well with Lua).
So this makes Settings accessible to Lua, and adds a simple GetSetting that just returns the base string, which lua can handle just fine as a number if that's what it is, and should be able to handle as a boolean (though I haven't tested that side heavily). Though simple this should work quite well for Lua.
=> [Small] Make Settings accessible to lua

README.md
As title says just fixes the 'Windows'/'Mac' links for the latest Unity Version
=> [Small] Fix the links to the version of unity we are using

CONTRIBUTING.md
Just updating the unity version, and I added a little caution to changing functions, properties, variables, or/and classes/structs.  With an obvious exception being for system restructures/overhauls or new systems.
=> [Small] Update version, and add little cautions to changing definitions

Assets/Editor/UnitTests/Models/BuildableComponentTest.cs, Assets/Editor/UnitTests/Models/Power/PowerGridTest.cs, Assets/Editor/UnitTests/Models/Power/PowerNetworkTest.cs, Assets/Scripts/Models/Buildable/Components/BuildableComponent.cs, Assets/Scripts/Models/Buildable/Components/FluidConnection.cs, Assets/Scripts/Models/Buildable/Components/GasConnection.cs, Assets/Scripts/Models/Buildable/Components/PowerConnection.cs, Assets/Scripts/Models/Buildable/Components/Visuals.cs, Assets/Scripts/Models/Buildable/Components/Workshop.cs, Assets/Scripts/Models/Buildable/Furniture.cs, Assets/Scripts/UtilityNetwork/Grid.cs, Assets/Scripts/UtilityNetwork/IPluggable.cs, Assets/Scripts/UtilityNetwork/PowerNetwork.cs, Assets/StreamingAssets/Data/Furniture.xml, Assets/StreamingAssets/Images/Furniture/Heater.xml, Assets/StreamingAssets/Images/Furniture/Heater.xml.meta, Assets/StreamingAssets/LUA/Furniture.lua
This allows to define furniture with fluctuating power input - meaning, if there is power shortage, instead of whole grid going down for these machines, machines will work at decreased efficiency (depending on available power)
E.g. here 2 smelters with power requirement of 2 (needed power = 4) being hooked on grid that provides 2 power. Efficiency varies from 50 to 60%. 
CanFluctuate flags are currently applied only on Oxygen Generator and Smelter.1
Changes:
- Requires with params is now RunConditions in components
- Power grid info now shows whether it's connected to grid with at least one producer (as Online/Offline is kind of confusing now with machines that have means to run but are not required)
- IPluggable now has more flags to support 'on demand' producers (fission reactor) …
=> Varying input/output (power/fluid) for components
